composewell/streamly

test/Main.hs

Not the best way to fix test code and also involves the usage of
partial function, but I guess that's fine for test code.

Fix test for composeAndComposeSimple function

---

Changelog.md
src/Streamly/Core.hs
src/Streamly/Streams.hs
test/Main.hs

This PR fixes #34 by correcting Zip and AsyncZip applicative instances.

fix: Zip/AsyncZip applicative instances

---

src/Streamly/Core.hs

This PR improve artificially the documentation !

(WIP) docs: typos

---

Changelog.md
benchmark/Main.hs
src/Streamly.hs
src/Streamly/Prelude.hs
src/Streamly/Streams.hs
src/Streamly/Tutorial.hs
test/Main.hs
test/Prop.hs

rename Streaming to IsStream and runStreaming to runStream

---

Changelog.md
benchmark/BenchmarkOps.hs
benchmark/Main.hs
src/Streamly/Prelude.hs
src/Streamly/Streams.hs
src/Streamly/Tutorial.hs
test/Prop.hs

rename each to fromFoldable

---

Changelog.md
benchmark/Main.hs
examples/loops.hs
examples/nested-loops.hs
examples/parallel-loops.hs
src/Streamly.hs
src/Streamly/Core.hs
src/Streamly/Examples/AcidRainGame.hs
src/Streamly/Examples/CirclingSquare.hs
src/Streamly/Examples/ListDirRecursive.hs
src/Streamly/Examples/SearchEngineQuery.hs
src/Streamly/Prelude.hs
src/Streamly/Streams.hs
streamly.cabal
test/Main.hs
test/Prop.hs

See the changelog for more details.
This is a work in progress. The alternative instance is yet to be implemented correctly. Tutorial needs to be updated as well.

Change the semantics of <> and <|>.

---

Changelog.md
benchmark/BenchmarkOps.hs
examples/loops.hs
examples/nested-loops.hs
examples/parallel-loops.hs
src/Streamly.hs
src/Streamly/Examples/AcidRainGame.hs
src/Streamly/Examples/CirclingSquare.hs
src/Streamly/Examples/ListDirRecursive.hs
src/Streamly/Examples/SearchEngineQuery.hs
src/Streamly/Prelude.hs
src/Streamly/Streams.hs
test/Main.hs
test/Prop.hs

This is on top of other not yet committed changes, see only the latest commit diff in this PR for changes specific to just this topic. This is work in progress, more changes to come. Fixes #33 .

Fix the default stream type to SerialT

---

Changelog.md
src/Streamly/Prelude.hs
test/Prop.hs

For addressing issue #74 
I am new to Haskell. Feel free to guide me towards a better implementation if possible. I have tested my implementation with `test/mapMB.hs` and the logic should be correct.

mapMaybe and mapMaybeM Implemented

---

Changelog.md
src/Streamly/Prelude.hs
src/Streamly/Streams/StreamK.hs
test/Prop.hs

Finally I got the time and patience to recommit my changes made for #43.

Approved prelude functions

---

src/Streamly/Tutorial.hs
streamly.cabal

Just some tweaks to the documentation.  Let me know if I should split it into multiple PRs, feel free to only merge a subset of the commits.

Documentation adjustments

---

src/Streamly/Streams/StreamD.hs

This is a work in progress PR for fixing https://github.com/composewell/streamly/issues/90
The major operations in `vector` for which the Skip constructor exists like `filter`, `drop` etc they need to be modified still and the whole thing needs benchmarking. 
Also does the CPS encoding need to change as well to allow transformation between the two alternate representations?

Add a skip constructor to the stream type

---

bench.sh
benchmark/BaseStreams.hs
benchmark/Chart.hs
benchmark/StreamDOps.hs
benchmark/StreamKOps.hs

1) Fix options parsing in charting program
2) Add a group-diff options to compare StreamD/K
3) Add more benchmarks to StreamD/K

Improve benchmarking of base streams

---

src/Streamly/Streams/Ahead.hs
src/Streamly/Streams/Async.hs
src/Streamly/Streams/Parallel.hs
src/Streamly/Streams/Serial.hs
src/Streamly/Streams/StreamD.hs
src/Streamly/Streams/StreamK.hs
src/Streamly/Streams/Zip.hs

Fixes https://github.com/composewell/streamly/issues/123
Need to add documentation about the use cases of these.

Add Foldable and Traversable instances for StreamD and StreamK

---

benchmark/BaseStreams.hs
benchmark/Chart.hs
benchmark/Linear.hs
benchmark/LinearOps.hs
benchmark/StreamDOps.hs
benchmark/StreamKOps.hs
src/Streamly/List.hs
src/Streamly/Prelude.hs
src/Streamly/Streams/Ahead.hs
src/Streamly/Streams/Async.hs
src/Streamly/Streams/Instances.hs
src/Streamly/Streams/Parallel.hs
src/Streamly/Streams/Prelude.hs
src/Streamly/Streams/Serial.hs
src/Streamly/Streams/StreamD.hs
src/Streamly/Streams/StreamK.hs
src/Streamly/Streams/Zip.hs
src/Streamly/String.hs
stack-7.10.yaml
stack-8.0.yaml
streamly.cabal
test/PureStreams.hs

Pure streams are streams with Identity as the base monad.
Added Eq/Ord/Read/Show/IsString/IsList instances for pure streams.

Add pure stream (list) instances

---

Changelog.md
benchmark/Linear.hs
benchmark/LinearOps.hs
src/Streamly/Prelude.hs
src/Streamly/Streams/Instances.hs
src/Streamly/Streams/Prelude.hs
src/Streamly/Streams/Serial.hs
src/Streamly/Streams/StreamD.hs
src/Streamly/Streams/StreamK.hs
src/Streamly/Streams/Zip.hs
src/Streamly/Tutorial.hs
test/Prop.hs

Adds many Prelude and Data.List functions mentioned in #11 . Also brings in most of the functions  supported by vector.

Prelude functions

---

src/Streamly/SVar.hs

Fix maxThreads being ignored

---

src/Streamly/Fold.hs
src/Streamly/Streams/StreamD.hs

Added grouped, span functions implementations which are undefined
before. 
-- Haven't added Prop tests, working on it

Implementation added for grouping, spanning Fold functions

---

src/Streamly/Streams/Parallel.hs

See the commit messages for more details.

Fix unbounded memory usage for ParallelT and improve performance

---

Changelog.md
src/Streamly/Prelude.hs
src/Streamly/SVar.hs
src/Streamly/Sink.hs
src/Streamly/Streams/Async.hs
src/Streamly/Streams/Parallel.hs
src/Streamly/Streams/SVar.hs
src/Streamly/Streams/StreamD.hs

See the changelog and haddock documentation for descriptions.

Add trace, tap and tee combinators

---

Changelog.md
benchmark/Linear.hs
benchmark/LinearOps.hs
examples/FileIOExamples.hs
examples/FileSinkServer.hs
examples/FromFileClient.hs
src/Streamly/Fold.hs
src/Streamly/Prelude.hs
streamly.cabal

Updated Changelog, the benchmarking ops, and the File IO example in README as well

Hide modules whose apis have not yet been finalised for 0.7.0

---

MAINTAINING.md
README.md
credits/CONTRIBUTORS.md
credits/COPYRIGHTS.md
credits/README.md
credits/Yampa-0.10.6.2.txt
credits/base-4.12.0.0.txt
credits/clock-0.7.2.txt
credits/foldl-1.4.5.txt
credits/pipes-concurrency-2.0.8.txt
credits/pipes-concurrency.txt
credits/transient-0.5.5.txt
credits/vector-0.12.0.2.txt
src/Streamly/Streams/StreamD.hs
streamly.cabal

I have added the names of the contributors to the library and licenses for the third party source code. 
I was not sure if just including the one line copyright notice is enough to meet the license conditions, so I included the full licenses from the original packages. The copyright notices are also mentioned in the respective files as well wherever we have included the code.
Any suggestions are welcome!

Add credits and copyrights

---

Changelog.md
benchmark/FileIO.hs
examples/FileSinkServer.hs
src/Streamly/Data/String.hs
src/Streamly/Fold/Types.hs
src/Streamly/Memory/Array.hs
src/Streamly/String.hs
streamly.cabal
test/String.hs

- String -> Data.String
- Make readIndex pure
- Fix the bug in lchunksOf

Some minor refactorings

---

benchmark/FileIO.hs
src/Streamly/Benchmark/FileIO/Array.hs
src/Streamly/Benchmark/FileIO/Stream.hs
src/Streamly/Data/String.hs
src/Streamly/Memory/Array.hs
src/Streamly/Memory/Array/Types.hs
src/Streamly/Streams/StreamD.hs
test/String.hs

- This PR adds decodeUtf8Lenient, decodeUtf8Arrays, decodeUtf8ArraysLenient functions. 
- Also simplifies the implementation of decoder and encoder functions. 
- The error messages do not provide context, these will be added in the future.

Add decodeUtf8 functions.

---

src/Streamly/Streams/StreamD.hs

* Simplify the state machine to carry minimal state
* reduce branches taken and improve branch prediction
With this change decode-utf8 has almost the same performance as decodeChar8 for
the ascii case. For the mixed unicode chars case as well the performance is
pretty good and not too far away from the ascii case.
Stream and array versions both fuse to similar core which pretty small and both
cases show exactly the same performance.

Simplify and optimize utf-8 decoding

---

.gitignore
src/Streamly/Benchmark/FileIO/Array.hs
src/Streamly/Benchmark/FileIO/Stream.hs
src/Streamly/FileSystem/FD.hs
src/Streamly/Internal/Data/Stream/StreamD/Type.hs
src/Streamly/Internal/Data/Unfold.hs
src/Streamly/Internal/Data/Unfold/Types.hs
src/Streamly/Internal/FileSystem/Handle.hs
src/Streamly/Internal/Memory/Array/Types.hs
src/Streamly/Internal/Network/Socket.hs
src/Streamly/Streams/StreamD.hs
streamly.cabal

1. Streamly.Streams.StreamD.Type -> Streamly.Internal.Stream.StreamD.Type
2. Changed all occurences accordingly

Move StreamD.Type to Internal

---

benchmark/FileIO.hs
benchmark/Linear.hs
benchmark/LinearAsync.hs
benchmark/LinearRate.hs
src/Streamly/Internal/Benchmark/FileIO/Array.hs
src/Streamly/Internal/Benchmark/FileIO/Stream.hs
src/Streamly/Internal/Benchmark/Prelude.hs
streamly.cabal

Move the Benchmark.* modules to Internal

---

Changelog.md
src/Streamly/Streams/StreamD.hs
test/Prop.hs

Fix bug in findIndices and add a regression test. Fixes #311.

---

src/Streamly/Internal/Memory/Array.hs
src/Streamly/Internal/Prelude.hs
src/Streamly/Streams/StreamD.hs

* unsafeRead
* headElse (head with a default)

Some routines for high performance code

---

src/Streamly/Internal/Control/Monad.hs
streamly.cabal

A utility function, just like "void" but also discards exceptions.

Add a "discard" function

---

examples/ListDir.hs
src/Streamly/Internal/Prelude.hs

Add concatMapTreeWith combinator

---

src/Streamly/Internal/Data/Stream/StreamK/Type.hs
src/Streamly/Internal/Prelude.hs

Experimental stuff for feedback and looping of stream output to inputs.

Add concatMap variants with feedback/looping

---

benchmark/Linear.hs
benchmark/LinearAsync.hs
benchmark/Nested.hs
benchmark/NestedConcurrent.hs
benchmark/NestedOps.hs
benchmark/Streamly/Benchmark/Prelude.hs
streamly.cabal

This is purely a reorganization of code by moving related code together and adding comments for subsections of code. There is no functionality change at all.

Reorganize prelude benchmarks

---

src/Streamly/Internal/Data/Stream/Serial.hs
src/Streamly/Internal/Data/Stream/StreamD/Type.hs

This PR
- implements custom definitions for SerialT's `<*>`, `*>`,`>>` .
- Use a weaker constraint on many instance definitions in StreamD.
Url for files changed because github won't recompute the diff.
https://github.com/composewell/streamly/compare/master...ap

Implement <*> and >> for SerialT via StreamD.

---

benchmark/Linear.hs
benchmark/Streamly/Benchmark/Prelude.hs
src/Streamly/Internal/Data/SVar.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Prelude.hs

These combinators should replace tapRate.

Combinators to count stream elements in a modular manner

---

benchmark/Linear.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Memory/Array.hs
src/Streamly/Internal/Memory/Array/Types.hs
src/Streamly/Memory/Ring.hs
test/Streamly/Test/Array.hs

LastN combinator

---

src/Streamly/Internal/Data/Fold.hs
streamly.cabal

Relax minimum bounds on containers.

---

src/Streamly/Internal/Data/Fold.hs

Distribute an input to void returning actions. This could be more efficient than just using `distribute` because there is no mutation involved in this case.

Add distribute_

---

benchmark/Linear.hs
benchmark/Streamly/Benchmark/Prelude.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Prelude.hs
streamly.cabal
test/Streamly/Test/Internal/Prelude.hs

The PR consists of `timelyTake` and `timelyDrop`.
TODO: Add tests and benchmarks

Time related combinators

---

src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Data/Stream/StreamD/Type.hs
src/Streamly/Internal/Data/Unicode/Stream.hs

In the following modules:
- Streamly.Internal.Data.Stream.StreamD
- Streamly.Internal.Data.Stream.StreamD.Type
- Streamly.Internal.Data.Unicode.Stream

Fix haddock copyright rendering in some modules.

---

src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Data/Unfold.hs

on exception handling the finalizer was left installed in the IORef to be run
by GC, this could cause the finalizer to be run twice.

clear the finalizer from IORef on exception

---

src/Streamly/Internal/Prelude.hs

1) We were taking a max of the latest timestamp and the timer maintained time
which is incorrect.
2) We were computing the timeout incorrectly making it twice the actual
timeout.
Also, maintain sessionCount in the state. We will use this later to put a limit
of the number of sessions.

Fix time measurement issue in classifySessionsBy

---

bench.sh
benchmark/BaseStreams.hs
benchmark/Chart.hs
benchmark/Concurrent.hs
benchmark/FileIO.hs
benchmark/Linear.hs
benchmark/Nested.hs
benchmark/NestedConcurrent.hs
benchmark/StreamDKOps.hs
benchmark/Streamly/Benchmark/FileIO/Stream.hs
streamly.cabal

And some other benchmark related fixes.

Use heap and stack limits on benchmarks

---

src/Streamly/Data/Unfold.hs
src/Streamly/FileSystem/FD.hs
src/Streamly/FileSystem/FDIO.hs
src/Streamly/FileSystem/Handle.hs
src/Streamly/Internal/Mutable/Prim/Var.hs
src/Streamly/Internal/Network/Inet/TCP.hs
src/Streamly/Internal/Network/Socket.hs
src/Streamly/Memory/Array.hs
src/Streamly/Memory/Malloc.hs
src/Streamly/Memory/Ring.hs

First round of cleanups for #406.

Hlint cleanup for Data, FileSystem and Memory directory

---

benchmark/lib/Streamly/Benchmark/Prelude.hs
benchmark/streamly-benchmarks.cabal

Some tests to check whether the SPEC constructor is removed in folds. We need add to add more.

Add some inspection tests for SPEC constructor

---

src/Streamly/Internal/Data/Stream/StreamD.hs
test/Streamly/Test/Array.hs

Fix lastN for n <= 0

---

MAINTAINING.md

Add a task to update the version in configure.ac along with running autoreconf.

Add an additional task before releasing

---

.travis.yml
examples/WordClassifier.hs
src/Streamly/FileSystem/IOVec.hsc
src/Streamly/Internal/Data/Fold.hs

Fix build on i386_HOST_ARCH

---

src/Streamly/Internal/Data/Fold/Types.hs

https://github.com/composewell/streamly/pull/449#discussion_r396201192

Remove improper instances from Fold as discussed in #449

---

.github/workflows/haskell.yml
streamly.cabal

Add support for build with GHC 8.10.1

---

benchmark/Chart.hs
benchmark/FileIO.hs
benchmark/Streamly/Benchmark/FileIO/Stream.hs
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Parser/Types.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Data/Unfold.hs
src/Streamly/Internal/Prelude.hs

1. Add parsers benchmarks to Chart.hs
2. factor out applicative operation as "splitWith"
3. rename parseChunks to "splitParse"
4. rename some parsers and add some more

Miscellaneous changes for parsers

---

Changelog.md
streamly.cabal

See commercialhaskell/stackage#5271.

Bump upper bound of QuickCheck

---

benchmark/Streamly/Benchmark/Data/Parser.hs
benchmark/Streamly/Benchmark/FileIO/Stream.hs
benchmark/streamly-benchmarks.cabal
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Parser/Tee.hs
src/Streamly/Internal/Data/Parser/Types.hs
src/Streamly/Internal/Data/Stream/Prelude.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Prelude.hs

parsers: peek, satisfy, eof, yield, yieldM, die, dieM
combinators: shortest, longest, alt, many, some, manyTill

Add Alternative instance, combinators and parsers

---

src/Streamly/Internal/Data/Fold/Types.hs
src/Streamly/Internal/Data/Parser/Tee.hs
src/Streamly/Internal/Data/Parser/Types.hs

The design documents can be viewed via haddock docs of the internal modules.

Add documentation on Fold/Parser design

---

docs/Build.md

Add note about details section

---

design/paths.rst

This document captures some initial thoughts on the requirements and design of a path handling module.

path representation and manipulation

---

benchmark/Streamly/Benchmark/Data/Parser.hs
benchmark/Streamly/Benchmark/Data/ParserD.hs
src/Streamly/Internal/Data/Parser/ParserD.hs
src/Streamly/Internal/Data/Parser/ParserD/Tee.hs
src/Streamly/Internal/Data/Parser/ParserD/Types.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Data/Zipper.hs

Add a new constructor to the Parser type. It fixes an issue with some of the combinators.

Yield and backtrack

---

Changelog.md
src/Streamly/Internal/Network/Inet/TCP.hs
src/Streamly/Internal/Network/Socket.hs

Also, close sockets promptly on exception.

Add connect and connectFrom

---

INSTALL.md

* Using `cabal install` is fraught with problems

Always use a cabal sandbox

---

src/Streamly/Internal/Data/Unfold.hs
src/Streamly/Internal/Prelude.hs

* Add fromStreamK
* fromStream: signature change, use fromStreamK as fromStreamD has very bad
performance characterstics.
* Add INLINEs to fromStream
* Remove fromStream1 and fromStream2 as they can be expressed trivially in
terms of fromStream and lmap.

Make changes to unfolds from stream

---

src/Streamly/Internal/Data/Array.hs

Fix primitive version bounds for when primitive is >= 0.7.1

---

INSTALL.md
credits/CONTRIBUTORS.md

- Use an informal register.
- Use the active voice.
- Make the guide accessible to people new to Haskell.
- Add a section suggesting a few next steps.

Rework the installation guide.

---

streamly.cabal
test/Main.hs
test/MaxRate.hs
test/Prop.hs
test/PureStreams.hs
test/Streamly/Test/Array.hs
test/Streamly/Test/Internal/Prelude.hs
test/String.hs

- Should we add MonadComprehensions, OverloadedStrings,
OverloadedLists to the list of default extensions?

Use default-extensions for tests.

---

.hlint.ignore
.hlint.yaml
src/Streamly/FileSystem/FDIO.hs
src/Streamly/Internal/BaseCompat.hs
src/Streamly/Internal/Control/Monad.hs
src/Streamly/Internal/Data/Parser/ParserD.hs
src/Streamly/Internal/Data/Parser/ParserD/Types.hs
src/Streamly/Internal/Data/Sink.hs
src/Streamly/Internal/Data/SmallArray/Types.hs
src/Streamly/Internal/Data/Stream/Prelude.hs
src/Streamly/Internal/Data/Unfold.hs
src/Streamly/Internal/Data/Unicode/Stream.hs
src/Streamly/Internal/Network/Socket.hs

Another round of clean ups for #406 
Signed-off-by: Sanchayan Maity <maitysanchayan@gmail.com>

Clean up hlint warnings

---

benchmark/Streamly/Benchmark/Data/Parser/ParserK.hs
benchmark/streamly-benchmarks.cabal

Add support to measure the performance of fromParserK API which converts ParserK representation to ParserD representation.

FromParserK benchmarks

---

src/Streamly/Internal/Memory/Array.hs
src/Streamly/Internal/Memory/Array/Types.hs
src/Streamly/Internal/Memory/Mutable/Array/Types.hs

Move fromAddr# and fromString# to the immutable Memory.Array module

---

benchmark/Streamly/Benchmark/Prelude/Serial.hs
examples/Split.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Prelude.hs

Use monadic action to get the initial state

---

src/Streamly/Internal/FileSystem/File.hs

* readChunks
* readChunksWithBufferOf
* readWithBufferOf
* foreverToChunksWithBufferOf
* foreverToChunks

Add some chunked file read APIs

---

benchmark/NanoBenchmarks.hs
benchmark/Streamly/Benchmark/Data/Fold.hs
benchmark/Streamly/Benchmark/Data/Parser.hs
benchmark/Streamly/Benchmark/Data/Parser/ParserD.hs
benchmark/Streamly/Benchmark/Data/Parser/ParserK.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/Read.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/ReadWrite.hs
benchmark/Streamly/Benchmark/Prelude/Parallel.hs
benchmark/Streamly/Benchmark/Prelude/Serial.hs
benchmark/Streamly/Benchmark/Prelude/WSerial.hs
benchmark/lib/Streamly/Benchmark/Prelude.hs
examples/FileIOExamples.hs
examples/HandleIO.hs
examples/ListDir.hs
examples/Rate.hs
examples/Split.hs
src/Streamly.hs
src/Streamly/Internal/Data/Stream/IsStream.hs
src/Streamly/Internal/Data/Stream/StreamK.hs
src/Streamly/Internal/Data/Unicode/Stream.hs
src/Streamly/Internal/FileSystem/Dir.hs
src/Streamly/Internal/FileSystem/Handle.hs
src/Streamly/Internal/Memory/ArrayStream.hs
src/Streamly/Prelude.hs
streamly.cabal
test/Main.hs
test/Streamly/Test/Array.hs
test/Streamly/Test/Internal/Data/Parser.hs
test/Streamly/Test/Internal/Data/Parser/ParserD.hs
test/Streamly/Test/Internal/Prelude.hs

Rename module Internal.Prelude to Internal.Data.Stream.IsStream.

---

src/Streamly/Internal/Data/Stream/StreamD.hs

@harendra-kumar I am unsure what the type signature of `gbracket` for `Unfold`s should be.

Pass the failed Stream as an argument to ghandle, gbracket 

---

Changelog.md
src/Streamly/Internal/Data/SVar.hs
src/Streamly/Internal/Data/Stream/Ahead.hs
src/Streamly/Internal/Data/Stream/Async.hs
src/Streamly/Internal/Data/Stream/SVar.hs
test/Main.hs

Capture the inner monad state and associate it with the work

---

benchmark/Streamly/Benchmark/Data/Unfold.hs
src/Streamly/Internal/Data/Unfold.hs
test/Streamly/Test/Data/Unfold.hs

Batch PR containing #721 #722

---

benchmark/Streamly/Benchmark/Data/Parser.hs
benchmark/Streamly/Benchmark/Data/Parser/ParserK.hs
benchmark/streamly-benchmarks.cabal
src/Streamly/Internal/Data/Stream/StreamD.hs
streamly.cabal

Reduce code-bloat in parsers due to -fspec-constr-recursive

---

src/Streamly/Internal/Data/Stream/IsStream.hs
test/Streamly/Test/Prelude/Serial.hs

Fix haddock for spliOnSuffixSeq
Add tests for splitOnSeq & spliOnSuffixSeq

Fix haddock & add tests for sequence split combinators

---

bench.sh

build_report_progs does not need an argument

Get rid of unecessary argument & extend --help with --raw

---

test/Streamly/Test/Prelude/Serial.hs

These tests were already written but commented out.

Enable splitOnSeq tests

---

benchmark/Streamly/Benchmark/FileSystem/Handle.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/Common.hs

dd is confusing to work with and has it's own idiosyncracies.

Avoid using dd, pipe data directly & truncate it using head

---

benchmark/Streamly/Benchmark/FileSystem/Handle/Read.hs
src/Streamly/Internal/Data/Stream/IsStream.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Memory/Ring.hs

This is based on the refactor by @adithyaov done for terminating folds change. The performance after that refactor regressed by manifold. This PR fixes the performance.
* The code fuses completely now, allocations are minimal.
* Performance is same as before

Refactor splitOnSeq

---

bench.sh

See `https://github.com/composewell/dev-tools` for git-cabal.

Support branch specific builds using git-cabal

---

benchmark/Streamly/Benchmark/Data/Parser.hs
src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Parser/ParserD.hs

takeEQ was not terminating promptly, it was holding up the output till
the next input even though it could have terminated earlier.

Fix takeEQ

---

benchmark/Streamly/Benchmark/Data/Array.hs
benchmark/Streamly/Benchmark/Data/Fold.hs
benchmark/Streamly/Benchmark/Prelude/Serial/Elimination.hs

Move Prelude benchmarks from Fold module to Prelude module

---

src/Streamly/Internal/Data/Fold/Types.hs

And some formatting changes. There are no functionality changes in this
commit.

Update docs, add unimplemented skeletons

---

src/Streamly/Internal/Data/Stream/IsStream.hs

Prelude.Serial/o-1-space/grouping/groups                  34683.66                     -50714.08

Add an INLINE pragma to IsStream.groups

---

test/Streamly/Test/Prelude/Serial.hs

These tests are implemented along with splitOnSeq and splitOnSuffixSeq

Add property tests for splitOn and splitOnSuffix

---

src/Streamly.hs
src/Streamly/Internal/Data/Array.hs
src/Streamly/Internal/Data/Array/Prim/MutTypesInclude.hs
src/Streamly/Internal/Data/Array/Storable/Foreign/Mut/Types.hs
src/Streamly/Internal/Data/Array/Storable/Foreign/Types.hs
src/Streamly/Internal/Data/Stream/StreamK.hs
src/Streamly/Internal/Data/Unfold.hs
src/Streamly/Internal/Network/Inet/TCP.hs

As part of terminating folds review.

Make misc formatting, stylistic, comment changes

---

design/module-organization.md

See the rendered doc here: https://github.com/composewell/streamly/blob/module-org/design/module-organization.md

update with new module org plans

---

.hlint.ignore
bin/targets.sh
hie.yaml
streamly.cabal
test/Streamly/Test/Common/Array.hs
test/Streamly/Test/Data/Fold.hs
test/Streamly/Test/FileSystem/Handle.hs
test/streamly-tests.cabal

…stdDev, variance, mconcat, foldMap, foldMapM, lookup, mapM, teeWithLength, teeWithMax, distribute, partition, unzip

Add test cases in Data.Fold and FileSystem.Handle modules

---

streamly.cabal

Remove conditional ghcjs build

---

src/Streamly/Internal/FileSystem/Event/Linux.hs
src/Streamly/Internal/FileSystem/Event/Windows.hs

Add Absolute Path to Windows and Linux Events

---

src/Streamly/Internal/Data/Stream/IsStream/Generate.hs

change fromListM to fromFoldable, add a rewrite rule for serial streams

---

src/Streamly/Internal/Data/IOFinalizer.hs
src/Streamly/Internal/Data/Stream/StreamD/Exception.hs
src/Streamly/Internal/Data/Unfold.hs
streamly.cabal

From StreamD/Exception module. This is a common functionality used in
Stream as well as in Unfold and can be used generally.

Factor out IOFinalizer module

---

test/Streamly/Test/Common/Array.hs
test/lib/Streamly/Test/Common.hs
test/lib/Streamly/Test/Prelude/Common.hs

Add more diagnostic information to debug better when tests fail.
Print the lists being compared in the fromListN test.
Added list length printing to know the length when the lists printed are large.

Add reverse' test

---

Changelog.md

Add release dates to Changelog.

---

src/Streamly/Internal/Data/Array/Foreign.hs
src/Streamly/Internal/Data/Array/Foreign/Mut/Types.hs
src/Streamly/Internal/Data/Array/Foreign/Types.hs
src/Streamly/Internal/Data/Array/Stream/Foreign.hs

Just added the API but have not used it yet.

Implement readRev to read an array in reverse order

---

design/cps-vs-direct.rst

It is quickly written so may have mistakes. The code is not compiler checked.

Add a doc illustrating CPS/direct style streams

---

benchmark/Streamly/Benchmark/FileSystem/Handle/Read.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/ReadWrite.hs
src/Streamly/Internal/Data/Stream/IsStream/Nesting.hs
src/Streamly/Internal/Data/Stream/StreamD/Type.hs

Need to run the benchmarks before merging.

Use foldMany1 in chunksOf instead of foldMany

---

src/Streamly/Internal/Data/Stream/IsStream/Nesting.hs

Add a template/signature for splitOnPrefix function.

Update docs of splitting combinators

---

src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/FileSystem/Event/Linux.hs
test/Streamly/Test/Data/Fold.hs
test/Streamly/Test/Data/Parser/ParserD.hs

It can be expressed as:
sliceSepByMax p n = sliceSepBy p . takeLE n

Remove sliceSepByMax

---

src/Streamly/Internal/Data/Stream/IsStream/Transform.hs

Some with trivial implementation are implemented, others are left
unimplemented with signatures for later implementation.

Add some filtering/buffering/insertion combinators

---

src/Streamly/Internal/Data/Time/TimeSpec.hsc
src/Streamly/Internal/FileSystem/IOVec.hsc

This should also fix build on armv7 wrt #961

Use WORD_SIZE_IN_BITS for Word32 guard

---

Changelog.md
benchmark/Streamly/Benchmark/Data/Fold.hs
src/Streamly/Data/Fold.hs
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Fold/Tee.hs
src/Streamly/Internal/Data/Fold/Types.hs
src/Streamly/Prelude.hs

Remove Applicative instance of Fold and release teeWith

---

benchmark/Streamly/Benchmark/Prelude/Serial/Transformation2.hs
src/Streamly/Internal/Data/Stream/IsStream/Nesting.hs

classifySessionsBy docs and signature update

---

benchmark/Streamly/Benchmark/Data/Parser.hs
benchmark/Streamly/Benchmark/Data/Parser/ParserD.hs
src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Parser/ParserD.hs
src/Streamly/Internal/Data/Parser/ParserD/Types.hs
test/Streamly/Test/Data/Parser.hs
test/Streamly/Test/Data/Parser/ParserD.hs

Change argument order in parser combinators 

---

benchmark/Streamly/Benchmark/Unicode/Stream.hs

Fix import error

---

src/Streamly/Internal/Data/Array.hs
src/Streamly/Internal/Data/Array/Foreign.hs
src/Streamly/Internal/Data/Array/Prim/MutTypesInclude.hs
src/Streamly/Internal/Data/Array/PrimInclude.hs
src/Streamly/Internal/Data/SmallArray.hs
src/Streamly/Internal/Data/Stream/IsStream/Common.hs
src/Streamly/Internal/Data/Stream/IsStream/Eliminate.hs
src/Streamly/Internal/Data/Stream/Prelude.hs
src/Streamly/Internal/Data/Stream/SVar.hs
src/Streamly/Internal/Data/Stream/StreamD/Eliminate.hs
src/Streamly/Internal/Data/Stream/StreamD/Nesting.hs
src/Streamly/Internal/Data/Stream/StreamD/Transform.hs
src/Streamly/Internal/Data/Stream/StreamD/Type.hs
src/Streamly/Internal/Data/Stream/StreamK.hs
src/Streamly/Internal/Unicode/Stream.hs
test/Streamly/Test/Data/Fold.hs
test/Streamly/Test/FileSystem/Handle.hs

Add parse and fold functions that return rest of the stream.

---

benchmark/Streamly/Benchmark/Data/Unfold.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/Read.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/ReadWrite.hs
benchmark/Streamly/Benchmark/Prelude/Serial/Split.hs
benchmark/Streamly/Benchmark/Unicode/Stream.hs
src/Streamly/Internal/Data/Unfold.hs
src/Streamly/Internal/Data/Unfold/Type.hs
src/Streamly/Internal/FileSystem/Dir.hs
src/Streamly/Internal/FileSystem/File.hs
src/Streamly/Internal/FileSystem/Handle.hs
src/Streamly/Internal/Network/Inet/TCP.hs
src/Streamly/Internal/Network/Socket.hs
test/Streamly/Test/Data/Unfold.hs

Rename Unfold.concat to Unfold.many 

---

Changelog.md
benchmark/Streamly/Benchmark/Data/Stream/StreamD.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/Read.hs
benchmark/Streamly/Benchmark/Prelude/Serial/Nested.hs
benchmark/Streamly/Benchmark/Prelude/WSerial.hs
design/optimization-guidelines.md
docs/Build.md
src/Streamly/Data/Unfold.hs
src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
src/Streamly/Internal/Data/Array/Foreign/Type.hs
src/Streamly/Internal/Data/Array/PrimInclude.hs
src/Streamly/Internal/Data/Array/Stream/Foreign.hs
src/Streamly/Internal/Data/Stream/IsStream/Common.hs
src/Streamly/Internal/Data/Stream/IsStream/Expand.hs
src/Streamly/Internal/Data/Stream/StreamD/Generate.hs
src/Streamly/Internal/Data/Stream/StreamD/Nesting.hs
src/Streamly/Internal/Data/Stream/StreamD/Transform.hs
src/Streamly/Internal/Data/Stream/StreamD/Type.hs
src/Streamly/Internal/Data/Stream/StreamK/Type.hs
src/Streamly/Internal/Data/Unfold.hs
src/Streamly/Internal/Data/Unfold/Type.hs
src/Streamly/Prelude.hs
test/Streamly/Test/Common/Array.hs
test/Streamly/Test/Data/Parser/ParserD.hs
test/lib/Streamly/Test/Prelude/Common.hs

Rename concatUnfold to unfoldMany 

---

Changelog.md
benchmark/Streamly/Benchmark/Data/Unfold.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/ReadWrite.hs
benchmark/Streamly/Benchmark/Prelude/Serial/Exceptions.hs
src/Streamly/Data/Unfold.hs
src/Streamly/Internal/Data/Unfold.hs
src/Streamly/Internal/Data/Unfold/Type.hs

Unfold docs

---

benchmark/Streamly/Benchmark/Data/Stream/StreamK.hs

default is `origin/master`
```
Generating reports for Data.Stream.StreamK...
Data.Stream.StreamK(cpuTime)
Benchmark                                                                    default(0)(μs) default(1) - default(0)(%)
---------------------------------------------------------------------------- -------------- --------------------------
Data.Stream.StreamK/o-1-space/mixed/take-map                                       13412.18                     +17.92
Data.Stream.StreamK/o-1-space/transformation/foldrS                                 3017.45                     +17.36
Data.Stream.StreamK/o-1-space/mixed/drop-map                                       13011.21                     +13.68
Data.Stream.StreamK/o-1-space/elimination/toNull                                    3005.66 …
```

Refactoring bench:StreamK

---

src/Streamly/Internal/Data/Array/Foreign.hs
test/Streamly/Test/Common/Array.hs

https://github.com/composewell/streamly/issues/921

Add a basic array slicing combinator

---

Changelog.md
benchmark/Streamly/Benchmark/Data/Stream/StreamK.hs
src/Streamly/Internal/Data/Stream/StreamK.hs
src/Streamly/Internal/Data/Stream/Zip.hs

https://github.com/composewell/streamly/issues/158

Fix zipWith to work concurrently according to the stream type

---

MAINTAINING.md
credits/CONTRIBUTORS.md
test/Streamly/Test/Prelude/Rate.hs
test/Streamly/Test/Prelude/Serial.hs
test/lib/Streamly/Test/Prelude/Common.hs
test/streamly-tests.cabal

- Update contributors list.
- Fix formatting in MAINTAINING.md.
- Fix tests under dev flag.

Miscellaneous 

---

src/Streamly/Internal/Data/Fold/Tee.hs

Remove mkT from Tee module

---

src/Streamly/Data/Fold.hs
src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
src/Streamly/Internal/Data/Array/Prim/MutTypesInclude.hs
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Fold/Type.hs
test/lib/Streamly/Test/Prelude/Common.hs

Rename fold constructors in Data.Fold 

---

benchmark/Streamly/Benchmark/Data/Array/Stream/Foreign.hs
benchmark/Streamly/Benchmark/Data/Parser/ParserD.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/Read.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/ReadWrite.hs
benchmark/streamly-benchmarks.cabal
hie.yaml
streamly.cabal

Purely a refactor of tests and benchmarks, no functional changes.

Move array stream bench/tests to separate modules

---

.hlint.ignore
benchmark/Streamly/Benchmark/Unicode/Stream.hs

Fix benchmark names, cleanup imports, fix hlint

---

benchmark/Streamly/Benchmark/Prelude/Serial/Transformation1.hs
src/Streamly/Data/Fold.hs
src/Streamly/Internal/Data/Array/Stream/Foreign.hs
src/Streamly/Internal/Data/Stream/IsStream/Expand.hs
src/Streamly/Internal/Data/Unfold.hs
src/Streamly/Internal/Network/Inet/TCP.hs
src/Streamly/Internal/Network/Socket.hs
src/Streamly/Network/Inet/TCP.hs
src/Streamly/Network/Socket.hs
src/Streamly/Prelude.hs
src/Streamly/Unicode/Stream.hs
test/Streamly/Test/Network/Inet/TCP.hs
test/Streamly/Test/Network/Socket.hs
test/Streamly/Test/Prelude/Serial.hs

* Exports some Internal APIs.
* Updates some docs
* Change signature of intercalate
Can review commit by commit.

New exports

---

src/Streamly/Internal/Unicode/Stream.hs

Pure refactor:
* Rearrange code in coherent sections
* Rename UTF8 decode states

Refactor Unicode.Stream module

---

src/Streamly/Internal/Unicode/Stream.hs

Refactor encodeUtf8 and encodeUtf8'

---

Changelog.md
INSTALL.md
README.md
docs/Overview.md
streamly.cabal

* Updated the README to have mostly example based illustration.
* Moved the unused parts of the old README to docs/Overview.md.

Update README for 0.8.0

---

README.md
benchmark/Streamly/Benchmark/Data/Fold.hs
benchmark/Streamly/Benchmark/Data/Unfold.hs
src/Streamly/Internal/Data/Array/Stream/Fold/Foreign.hs
src/Streamly/Internal/Data/Binary/Decode.hs
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Fold/Tee.hs
src/Streamly/Internal/Data/Fold/Type.hs
src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Parser/ParserD.hs
src/Streamly/Internal/Data/Parser/ParserD/Type.hs
src/Streamly/Internal/Data/Parser/ParserK/Type.hs
src/Streamly/Internal/Data/Pipe.hs
src/Streamly/Internal/Data/Unfold.hs
src/Streamly/Internal/Data/Unfold/Type.hs
src/Streamly/Internal/FileSystem/Event/Linux.hs
test/Streamly/Test/Data/Parser.hs
test/Streamly/Test/Data/Parser/ParserD.hs
test/Streamly/Test/Data/Unfold.hs

Renamed yield, yieldM in Unfold, Fold, Parser code to be consistent with the new names

Rename yield, yieldM to fromPure, fromEffect.

---

docs/Build.md

Just to make the doc presentable.

Add a title and contain all sections in it

---

INSTALL.md
README.md
docs/Build.md
streamly.cabal

Add streamly homepage link to cabal file.

Move links references to one place

---

src/Streamly/Tutorial.hs

* Move setup and imports together, fix WAsync example
* Remove redundant imports
* Remove @..@ blocks
* Convert more snippets to doctest
* Edit concurrent streams examples
* Reformat code snippets
* Shorten the length of code lines
* Remove search query example

Rework the Streamly.Tutorial module

---

src/Streamly/Console/Stdio.hs
src/Streamly/Data/Array/Foreign.hs
src/Streamly/Data/Fold.hs
src/Streamly/Data/Fold/Tee.hs
src/Streamly/Data/Unfold.hs
src/Streamly/FileSystem/Handle.hs
src/Streamly/Internal/Data/Array.hs
src/Streamly/Internal/Data/Array/Stream/Foreign.hs
src/Streamly/Internal/Data/Binary/Decode.hs
src/Streamly/Internal/Data/List.hs
src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Stream/IsStream.hs
src/Streamly/Internal/Data/Time/Clock.hs
src/Streamly/Internal/Data/Time/Units.hs
src/Streamly/Internal/FileSystem/Dir.hs
src/Streamly/Internal/FileSystem/Event/Darwin.hs
src/Streamly/Internal/FileSystem/Event/Linux.hs
src/Streamly/Internal/FileSystem/Event/Windows.hs
src/Streamly/Internal/FileSystem/File.hs
src/Streamly/Network/Inet/TCP.hs
src/Streamly/Network/Socket.hs
src/Streamly/Prelude.hs
src/Streamly/Unicode/Stream.hs

Remove all `Stability: experimental`?
```
find src -name "*.hs" -exec sed -i -r -e '/^-- Stability.*: experimental$/d' {} \;
```

Add "released" and "pre-release" to the "Stability" key in modules

---

src/Streamly/Internal/BaseCompat.hs
src/Streamly/Internal/Data/Array/Foreign.hs
src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
src/Streamly/Internal/Data/Array/Stream/Foreign.hs
src/Streamly/Internal/Data/Stream/IsStream/Transform.hs
src/Streamly/Internal/FileSystem/Event/Darwin.hs
src/Streamly/Internal/FileSystem/Event/Linux.hs
src/Streamly/Internal/FileSystem/FD.hs
src/Streamly/Internal/FileSystem/Handle.hs
src/Streamly/Internal/Network/Socket.hs

Replace withForeignPtr by unsafeWithForeignPtr

---

.packcheck.ignore
Changelog.md
README.md
benchmark/bench-report/BenchReport.hs
dev/MAINTAINING.md
dev/container-api.md
docs/building.md
src/Streamly/Data/Fold.hs
streamly.cabal

Mostly changes found during release process.

Misc changes

---

bin/run-ci.sh

I am using this to do pre-release ci testing.

Create a release ci suite

---

test/Streamly/Test/Data/Fold.hs

Add test cases for newly added functions in Internal.Data.Fold

---

src/Streamly/Internal/Data/Fold.hs

Convert the remaining examples to doctest

---

src/Streamly/Internal/Data/Stream/IsStream/Common.hs

Since the property test code is a bit long I added it in a separate section so that it is not included in haddock but gets tested.

Add a property test for splitOnSeq

---

src/Streamly/Internal/Data/Stream/IsStream/Exception.hs
src/Streamly/Internal/Data/Stream/IsStream/Expand.hs
src/Streamly/Internal/Data/Stream/IsStream/Transform.hs
src/Streamly/Internal/Data/Stream/StreamD/Exception.hs
src/Streamly/Internal/Data/Unfold.hs

Need to check any perf impact due to `bracket` changes.

Some changes for streamly process

---

.github/workflows/haskell.yml
src/Streamly/FileSystem/Handle.hs
src/Streamly/Internal/Data/Array/Stream/Foreign.hs
src/Streamly/Internal/Data/Array/Stream/Mut/Foreign.hs
src/Streamly/Internal/Data/Stream/IsStream/Common.hs
src/Streamly/Internal/Data/Stream/IsStream/Exception.hs
src/Streamly/Internal/Data/Stream/IsStream/Transform.hs
src/Streamly/Internal/Data/Unfold.hs
src/Streamly/Internal/FileSystem/Handle.hs

These changes are mostly motivated by the FileSystem.Handle changes, so in the same PR:
* update documentation in some Stream functions
* Add some unimplemented function in Data.Unfold
* Update some notes in array stream module

Update documentation and expose a few APIs in FileSystem.Handle

---

src/Streamly/Internal/Data/Array.hs

Review commit by commit, first commit is rearrangement of code, second is enhancement.

Refactor and add getIndexUnsafe

---

benchmark/Streamly/Benchmark/Data/Fold.hs
src/Streamly/Internal/Data/Array/Stream/Foreign.hs
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Fold/Type.hs

Remove map from Internal.Data.Fold

---

benchmark/Streamly/Benchmark/Data/Fold.hs
src/Streamly/Data/Fold.hs
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Fold/Type.hs
test/Streamly/Test/Data/Fold.hs

Implement undefined functions of Fold.Types module

---

.github/workflows/haskell.yml
bin/targets.sh
test/Streamly/Test/Unicode/Char.hs
test/streamly-tests.cabal

Fix the coverage build temporarily

---

src/Streamly/Internal/FileSystem/File.hs

Implement readChunksFromToWith

---

.hlint.yaml
src/Streamly/Internal/Unicode/Char/Parser.hs
streamly.cabal

Addresses #1199 except Implement `inClass` predicate in Unicode.Char module
See #1290 
See  #1291

Add Numeric and Char parsers

---

src/Streamly/Internal/Data/Fold.hs

Implement scan for folds

---

test/Streamly/Test/Prelude/Serial.hs

Add tests for sort and mergeBy

---

benchmark/Streamly/Benchmark/Data/Parser/ParserD.hs
benchmark/Streamly/Benchmark/Prelude/Merge.hs
src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Parser/ParserD.hs
src/Streamly/Internal/Data/Stream/IsStream/Top.hs
test/Streamly/Test/Prelude/Serial.hs

Implementation of groupByRollingEither

---

benchmark/Streamly/Benchmark/Data/Array.hs
src/Streamly/Internal/Data/Array.hs
src/Streamly/Internal/Data/Ring.hs
streamly.cabal

Implement a polymorphic ring buffer

---

dev/MAINTAINING.md

With prefixes for different categories of labels.

Update label management section

---

src/Streamly/Internal/Data/Array/Foreign.hs
src/Streamly/Internal/Data/Pipe.hs
src/Streamly/Internal/Data/Ring/Foreign.hs
src/Streamly/Internal/Data/Stream/StreamD/Nesting.hs
streamly.cabal

Rename Streamly.Internal.Ring.Foreign module

---

src/Streamly/Internal/Unicode/Stream.hs

This makes it more modular and the unfold is reusable. The benchmarks do not show significant degradation. The encode/decode utf8 benchmark is down by 3% and encode/decodeArray down by 10%.
```
Unicode.Stream(cpuTime)
Benchmark                                                                                        default(0)(ms) default(1) - default(0)(%)
------------------------------------------------------------------------------------------------ -------------- --------------------------
Unicode.Stream/o-1-space/decode-encode/toChunks/encodeUtf8' . decodeUtf8Arrays (1/10)                    124.69                      +9.26
Unicode.Stream/o-1-space/decode-encode/encodeUtf8 . decodeUtf8 (1/10)                                    136.58                      +2.49
Unicode.Stream(allocated) …
```

Use unfold to implement utf8 encode

---

benchmark/Streamly/Benchmark/Data/Parser/ParserD.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/ReadWrite.hs
src/Streamly/Internal/Data/Array/Foreign.hs
src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
src/Streamly/Internal/Data/Array/Foreign/Type.hs
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Fold/Type.hs
src/Streamly/Internal/Data/Maybe/Strict.hs
src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Parser/ParserD.hs
src/Streamly/Internal/Data/Stream/IsStream/Common.hs
src/Streamly/Internal/Data/Stream/IsStream/Expand.hs
src/Streamly/Internal/Data/Stream/IsStream/Reduce.hs
src/Streamly/Internal/Data/Stream/IsStream/Type.hs
src/Streamly/Internal/Data/Tuple/Strict.hs
src/Streamly/Internal/FileSystem/Dir.hs
src/Streamly/Internal/FileSystem/FD.hs
src/Streamly/Internal/FileSystem/File.hs
src/Streamly/Internal/FileSystem/Handle.hs
src/Streamly/Internal/Network/Inet/TCP.hs
src/Streamly/Internal/Network/Socket.hs

Continuation of PR #1430 which was accidentally closed and could not be reopened.
I have removed the mutual recursion related fixes until those are properly tested. This PR contains rest of the fixes from the above PR.

GHC 9.2 related performance fixes

---

src/Streamly/Internal/Data/Array/Stream/Fold/Foreign.hs

- fromParser -> fromParserD
- Reimplemented fromParser in terms of fromParserD

Fix the nomenclature in array stream folds

---

benchmark/bench-report/BenchReport.hs
benchmark/bench-report/default.nix

- Fix `default.nix`
- Fix some warnings

Changes for bench report 

---

benchmark/Streamly/Benchmark/Unicode/Stream.hs
src/Streamly/Internal/Unicode/Stream.hs

The two benchmarks doing the same are below,
```
decodeUtf8 = parseManyD parseCharUtf8D
```
```
Generating reports for Unicode.Stream...
Unicode.Stream(cpuTime)
Benchmark                                                                                            default(ms)
---------------------------------------------------------------------------------------------------- -----------
All.Unicode.Stream/o-1-space.decode-encode.encodeUtf8 . parseManyD parseCharUtf8D (1/10)                  589.66
All.Unicode.Stream/o-1-space.decode-encode.encodeUtf8 . decodeUtf8 (1/10)                                 141.05
Unicode.Stream(Allocated)
Benchmark                                                                                            default(MiB) …
```

Add character based unicode decoding

---

benchmark/Streamly/Benchmark/Data/Array/Foreign/Mut.hs
core/src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
test/Streamly/Test/Data/Array/Foreign.hs

Add strip API to  Foreign Array

---

benchmark/Streamly/Benchmark/Data/Array/Foreign/Mut.hs
core/src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs

Implement Array modifyIndices may accept index as argument

---

core/src/Streamly/Internal/Data/Fold.hs

Convert demux/classify doc snippets to docspec

Update docs of demux and classify

---

core/src/Streamly/Internal/Data/Unfold.hs
docs/API-changelog.txt
src/Streamly/Data/Unfold.hs

Downgrade Monad to Applicative

---

src/Streamly/Internal/Data/Stream/IsStream/Top.hs

Fix SampleBurstEnd

---

benchmark/lib/Streamly/Benchmark/Common/Handle.hs
benchmark/streamly-benchmarks.cabal
cabal.project.ghc-head
core/streamly-core.cabal
src/Streamly/Internal/Unicode/Stream.hs
streamly.cabal

Increase benchmark memory for ghc-9.5

Allow base-4.17, ghc-9.4

---

core/src/Streamly/Internal/Data/Stream/StreamD/Eliminate.hs

Fix fusion issue in isSubsequenceOf, isPrefixOf, stripPrefix, the.
A subset of PR #1713 as some inspection tests are failing in that. Hopefully these commits are fine wrt that.

Fix fusion issue in multi-stream folds

---

core/src/Streamly/Internal/Data/Stream/StreamD/Eliminate.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Type.hs

Use SPEC for stream fold oeprations (recursive functions)

---

benchmark/Streamly/Benchmark/Data/Unfold.hs
benchmark/bench-runner/Main.hs
benchmark/streamly-benchmarks.cabal
core/src/Streamly/Internal/Data/Stream/Bottom.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Generate.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Type.hs
core/src/Streamly/Internal/Data/Unfold.hs
core/src/Streamly/Internal/Data/Unfold/Type.hs
core/streamly-core.cabal
src/Streamly/Data/Unfold.hs
src/Streamly/Internal/Data/Stream/IsStream/Reduce.hs
targets/Targets.hs
test/Streamly/Test/Data/Unfold.hs

This is to study where unfold generates streams do not perform as well as direct stream implementation.

Add a build flag to use unfolds for stream generation

---

benchmark/Streamly/Benchmark/Data/Unfold.hs
core/src/Streamly/Internal/Data/Array/Unboxed/Mut.hs
core/src/Streamly/Internal/Data/Unfold.hs
core/src/Streamly/Internal/Data/Unfold/Type.hs
src/Streamly/Data/Unfold.hs
src/Streamly/Internal/FileSystem/Dir.hs
test/Streamly/Test/Data/Unfold.hs

* rename mapmWithInput to mapM2
* add map2

Implement many2 and crossWith in terms of many2

---

core/src/Streamly/Internal/Data/Stream/Generate.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Generate.hs
core/src/Streamly/Internal/Data/Unfold.hs
src/Streamly/Internal/Unicode/Stream.hs

fixes:https://github.com/composewell/streamly/issues/1729

Add API to generate Stream from memory Address

---

.hlint.ignore
core/src/Streamly/Internal/Data/Parser/ParserD/Type.hs
core/src/Streamly/Internal/Data/Parser/ParserK/Type.hs

See the commit messages for change description.

ParserK refactor

---

benchmark/Streamly/Benchmark/Data/Parser.hs
benchmark/Streamly/Benchmark/Data/Parser/ParserD.hs
benchmark/Streamly/Benchmark/Data/Parser/ParserK.hs
benchmark/streamly-benchmarks.cabal
core/src/Streamly/Internal/Data/Array/Stream/Fold/Foreign.hs
core/src/Streamly/Internal/Data/Array/Stream/Mut/Foreign.hs
core/src/Streamly/Internal/Data/Parser.hs
core/src/Streamly/Internal/Data/Parser/ParserD.hs
core/src/Streamly/Internal/Data/Parser/ParserD/Tee.hs
core/src/Streamly/Internal/Data/Parser/ParserD/Type.hs
core/src/Streamly/Internal/Data/Parser/ParserK/Type.hs
core/src/Streamly/Internal/Data/Producer/Source.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Eliminate.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Nesting.hs
core/src/Streamly/Internal/Data/Stream/StreamK.hs
src/Streamly/Internal/Data/Array/Stream/Foreign.hs
src/Streamly/Internal/Data/Binary/Decode.hs
src/Streamly/Internal/FileSystem/Event/Windows.hs
src/Streamly/Internal/Unicode/Stream.hs
test/Streamly/Test/Data/Parser.hs
test/Streamly/Test/Data/Parser/ParserD.hs
test/streamly-tests.cabal

Change the type of parser "extract" function to "Step"

---

core/src/Streamly/Data/Stream.hs
core/src/Streamly/Internal/Data/Stream/Bottom.hs
core/src/Streamly/Internal/Data/Stream/Eliminate.hs
core/src/Streamly/Internal/Data/Stream/Expand.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Nesting.hs
src/Streamly/Prelude.hs

Organize the export list of Streamly.Data.Stream

---

core/src/Streamly/Internal/Data/Fold/Type.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Type.hs

And a "done" checking function for folds.

Add a foldStream signature

---

src/Streamly/Internal/FileSystem/File.hs

Fixes:https://github.com/composewell/streamly/issues/1840

Remove IsStream imports from FileSystem.File module

---

src/Streamly/Internal/FileSystem/Event/Linux.hs
src/Streamly/Internal/FileSystem/Event/Windows.hs

Fixes:https://github.com/composewell/streamly/issues/1839

Remove IsStream import from FileSystem.Event.* modules 

---

benchmark/Streamly/Benchmark/Data/Stream/Transform.hs
src/Streamly/Internal/Data/Stream/IsStream/Common.hs
src/Streamly/Internal/Data/Stream/IsStream/Expand.hs
src/Streamly/Internal/Data/Stream/IsStream/Generate.hs
src/Streamly/Internal/Data/Stream/IsStream/Parallel.hs
src/Streamly/Internal/Data/Stream/IsStream/Transform.hs
src/Streamly/Internal/Data/Stream/IsStream/Type.hs
streamly.cabal

In preparation for adding a new channel based implementation of Parallel module.

Move the Parallel module under IsStream

---

benchmark/Streamly/Benchmark/Data/Stream/AsyncOrdered.hs
benchmark/streamly-benchmarks.cabal
src/Streamly/Internal/Data/Stream/Async.hs
src/Streamly/Internal/Data/Stream/Async/Channel.hs
src/Streamly/Internal/Data/Stream/Async/Channel/Append.hs
src/Streamly/Internal/Data/Stream/Async/Channel/Operations.hs
src/Streamly/Internal/Data/Stream/Async/Channel/Type.hs
src/Streamly/Internal/Data/Stream/Channel/Types.hs
src/Streamly/Internal/Data/Stream/Channel/Worker.hs
targets/Targets.hs
test/Streamly/Test/Data/Stream/Async.hs

This is the equivalent of the Ahead style streams.

Implement an "ordered" option in concurrent streams

---

core/src/Streamly/Data/Stream.hs
core/src/Streamly/Internal/Data/Stream/Generate.hs

Fixes:https://github.com/composewell/streamly/issues/1919

Add repeatM to Streamly.Data.Stream module

---

core/src/Streamly/Internal/Data/Stream/Bottom.hs
core/src/Streamly/Internal/Data/Stream/Reduce.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Type.hs

* Run the fold only when the stream is non-empty

Fix foldMany documentation and behavior

---

core/src/Streamly/FileSystem/Dir.hs
core/streamly-core.cabal

Fix:https://github.com/composewell/streamly/issues/2160

Expose filesystem dir module

---

core/src/Streamly/FileSystem/File.hs
core/src/Streamly/Internal/FileSystem/File.hs
core/streamly-core.cabal

Fix:https://github.com/composewell/streamly/issues/2160

Expose filesystem file module

---

core/src/Streamly/Internal/Data/Stream/Bottom.hs
core/src/Streamly/Internal/Data/Stream/Lift.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Lift.hs
core/src/Streamly/Internal/Data/Stream/Transform.hs
core/src/Streamly/Internal/Data/Stream/Transformer.hs
core/streamly-core.cabal

These ops do not depend on the "transformers" package.

Add generic inner monad lifting ops

---

core/src/Streamly/Internal/Data/Builder.hs
core/src/Streamly/Internal/Data/Unboxed.hs
core/streamly-core.cabal

For building instances for the Unbox type class

Add genericPeekByteIndex and genericPokeByteIndex

---

core/src/Streamly/Internal/Data/Stream/Expand.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Type.hs
core/src/Streamly/Internal/FileSystem/Dir.hs
core/streamly-core.cabal

Some of these are experimental.

Refactor, rename, add tree/graph traversal combinators

---

.hlint.ignore
test/Streamly/Test/Data/Array/Stream.hs
test/Streamly/Test/Data/Parser/Chunked.hs
test/Streamly/Test/Data/Parser/ParserD.hs
test/Streamly/Test/Data/Stream/Concurrent.hs
test/Streamly/Test/FileSystem/Event/Common.hs
test/Streamly/Test/Network/Inet/TCP.hs
test/Streamly/Test/Network/Socket.hs
test/Streamly/Test/Prelude/Serial.hs
test/Streamly/Test/Unicode/Stream.hs
test/streamly-tests.cabal

Only test cases with flag "use-streamly-core" is fixed in this commit.

Fix testcases after  remove rewrite rules.

---

benchmark/Streamly/Benchmark/Data/Stream.hs
benchmark/Streamly/Benchmark/Data/Stream/StreamD.hs
core/src/Streamly/Data/Stream.hs
core/src/Streamly/Data/StreamK.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Transform.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Type.hs

For fixing the benchmark results in streaming-benchmarks suite.

Fix fmap perf, add some scan, fold ops in Stream, some ops in StreamK

---

docs/User/HowTo/streamly-vs-async.md
docs/User/HowTo/streamly-vs-lists.md
docs/User/Tutorials/ConcurrentStreams.hs
docs/User/Tutorials/ReactiveProgramming.hs
docs/User/Tutorials/Tutorial.hs

These need to be either removed or updated.

Add obsolete message, in some outdated tutorials

---

core/LICENSE

Remove license that are not applicable.

Change license to regular file

---

core/streamly-core.cabal

https://github.com/composewell/streamly/issues/2342

Remove use-c-malloc flag from streamly-core

---

test/streamly-tests.cabal

https://github.com/composewell/streamly/issues/2332

Disable Linux event test using dev flag

---

core/src/Streamly/Data/Parser.hs

fixes:https://github.com/composewell/streamly/issues/2362

Expose groupByRolling and groupByRollingEither parsers

---

src/Streamly/Internal/Control/ForkLifted.hs
src/Streamly/Internal/Data/Fold/Concurrent/Channel/Type.hs
src/Streamly/Internal/Data/Stream/Channel/Types.hs

As per @adithyaov’s suggestions here: https://github.com/composewell/streamly/pull/2400
(See also https://github.com/composewell/streamly/issues/2405.)

Minor function rename & comment changes

---

core/src/Streamly/Data/MutArray.hs
core/src/Streamly/Internal/Data/Array/Mut/Type.hs

Fixes:https://github.com/composewell/streamly/issues/2353

Expose unsafe mutable array APIs

---

core/src/Streamly/Data/Stream.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Nesting.hs

Fixes:https://github.com/composewell/streamly/issues/2347

Expose wordsBy from Data.Stream module

---

core/src/Streamly/Data/Stream.hs

https://github.com/composewell/streamly/issues/2352

Expose splitOn and chunksSplitOn

---

benchmark/Streamly/Benchmark/Data/Fold/Window.hs
core/src/DocTestDataFold.hs
core/src/DocTestDataStream.hs
core/src/Streamly/Internal/Data/Fold.hs
core/src/Streamly/Internal/Data/Fold/Combinators.hs
core/src/Streamly/Internal/Data/Fold/Window.hs
core/streamly-core.cabal
test/Streamly/Test/Data/Fold/Window.hs

Add window prefix to combinators in Fold.Window module (#2517)

---

core/src/Streamly/Internal/Data/Stream/StreamK/Transformer.hs
core/src/Streamly/Internal/Data/StreamK.hs
core/streamly-core.cabal

…from core/src/Streamly/Internal/Data/Stream/StreamK.hs

export StreamK.Transformer

---

benchmark/Streamly/Benchmark/Data/Serialize.hs
benchmark/Streamly/Benchmark/Data/Serialize/RecCompatible.hs
benchmark/Streamly/Benchmark/Data/Serialize/RecNonCompatible.hs
core/src/Streamly/Data/Serialize.hs
core/src/Streamly/Internal/Data/Serialize/TH.hs
core/src/Streamly/Internal/Data/Serialize/TH/Bottom.hs
core/src/Streamly/Internal/Data/Unbox/TH.hs
test/Streamly/Test/Data/Serialize.hs
test/Streamly/Test/Data/Serialize/CompatV0.hs
test/Streamly/Test/Data/Serialize/CompatV1.hs
test/Streamly/Test/Data/Unbox.hs
test/Streamly/Test/Data/Unbox/TH.hs

Add ability to not use any INLINE pragma on size

---

core/docs/Changelog.md
core/src/Streamly/Internal/Data/Stream/Generate.hs
core/src/Streamly/Internal/Data/Stream/Type.hs

streamly-core: Add infixr 5 fixity for cons, consM

---

.circleci/config.yml
.github/workflows/haskell.yml
core/src/Streamly/Internal/Data/Array/Stream.hs
core/src/Streamly/Internal/Data/Array/Type.hs
core/src/Streamly/Internal/Data/MutArray/Type.hs
core/src/Streamly/Internal/Data/MutByteArray/Type.hs
core/src/Streamly/Internal/Data/Stream/Nesting.hs
core/src/Streamly/Internal/Data/StreamK.hs
core/src/Streamly/Internal/Data/StreamK/Type.hs
src/Streamly/Internal/Data/Stream/IsStream/Reduce.hs

* Some of these are updates required for better performance for directory traversal.
* Also, fixed a bug in pinnedFromList to generate pinned arrays.
* The rest of the changes are some cleanups

Some fixes and updates to Array and Array stream modules

---

core/src/Streamly/Internal/Data/MutArray/Stream.hs

We already allocated the right amount of space, using spliceUnsafe will generate lesser code, better for fusion and compilation, also tiny bit of additional efficiency.

Use spliceUnsafe instead of splice

---

core/src/Streamly/Internal/Data/MutArray/Stream.hs

splice reallocates every time, while we can just allocate the array once.

Change splice to spliceUnsafe

---

core/src/DocTestDataArray.hs
core/src/Streamly/Internal/Data/Array.hs
core/src/Streamly/Internal/Data/Array/Stream.hs
core/src/Streamly/Internal/Data/Array/Type.hs
core/src/Streamly/Internal/Data/MutArray.hs
core/src/Streamly/Internal/Data/MutArray/Stream.hs
core/src/Streamly/Internal/Data/MutArray/Type.hs
core/src/Streamly/Internal/Data/Stream/Transform.hs
src/Streamly/Internal/Data/Stream/IsStream/Common.hs

Prepare to deprecate and remove the Array/Stream module.

Move functions from Array/Stream module to Array module

---

core/src/DocTestFileSystemHandle.hs
core/src/Streamly/Data/Array.hs
core/src/Streamly/Internal/Data/Array.hs
core/src/Streamly/Internal/Data/Array/Type.hs
core/src/Streamly/Internal/FileSystem/File.hs
core/src/Streamly/Internal/FileSystem/Handle.hs
src/Streamly/Internal/Network/Inet/TCP.hs
src/Streamly/Internal/Network/Socket.hs
test/Streamly/Test/Data/Array.hs

Export create/createOf from Array module
Rearrange exports in Array module

Rename write* to create* in Array module (2)

---

core/src/Streamly/Internal/Data/Array.hs
core/src/Streamly/Internal/Data/Array/Type.hs

On getIndices, flattenArrays etc.

Add INLINE pragma on some deprecated functions

---

src/Streamly/Internal/Network/Inet/TCP.hs

Add pipeChunks function to do transformation on chunks.

Add pipeChunks transformation function

---

core/src/Streamly/Internal/Data/Array/Generic.hs
core/src/Streamly/Internal/Data/Array/Type.hs
core/src/Streamly/Internal/Data/MutArray/Type.hs
core/src/Streamly/Internal/Data/Stream/Generate.hs
core/src/Streamly/Internal/Unicode/Stream.hs

Deprecate fromByteStr and rename it to fromCString

Add fromW16CString, rename fromByteStr

---

core/src/Streamly/Internal/Data/Fold/Window.hs
core/src/Streamly/Internal/Data/Ring.hs

Move slidingWindow to the Fold.Window module

---

.github/workflows/haskell.yml
benchmark/streamly-benchmarks.cabal
src/Streamly/Internal/FileSystem/Event/Darwin.hs
stack.yaml
streamly.cabal
test/streamly-tests.cabal

Change 8.10.7 CI to cabal
Remove the redundant 9.8.1 -Werror CI

Add 9.8.2 macos stack CI

---

core/src/Streamly/Internal/Data/Array/Type.hs
core/src/Streamly/Internal/Data/MutArray/Lib.c
core/src/Streamly/Internal/Data/MutArray/Type.hs
core/src/Streamly/Internal/Data/MutByteArray/Type.hs
core/src/Streamly/Internal/Data/RingArray.hs
core/src/Streamly/Internal/Data/Unbox.hs
test/Streamly/Test/Data/Array.hs
test/Streamly/Test/Data/RingArray.hs
test/lib/Streamly/Test/Common.hs

- Fix the enum instance for IOSubSystem
- Fix array pin-ness bug
- Add test cases for from(W16)CString#

Multiple issue resolution

---

core/src/Streamly/Internal/FileSystem/Posix/Errno.hs
core/src/Streamly/Internal/FileSystem/Posix/File.hs
core/src/Streamly/Internal/FileSystem/Posix/ReadDir.hsc
core/streamly-core.cabal

It turns out to be slower, but I am keeping the code for future experiments.

Try openat call for directory traversing

---

src/Streamly/Internal/FileSystem/Event/Darwin.c

* Remove deprecated runLoop APIs, replace with GCD
* Improve error handling

Update macOS fs event handling code

---

core/src/Streamly/Internal/FileSystem/Path/Common.hs
core/src/Streamly/Internal/FileSystem/PosixPath.hs

Commit 2 is non-functional but changes the API of an internal function

Fix allowRelativeEquality option for leading relative roots
