composewell/streamly

.hlint.yaml
src/Streamly/Prelude.hs
src/Streamly/SVar.hs
src/Streamly/Streams/Ahead.hs
src/Streamly/Streams/Async.hs
src/Streamly/Streams/Parallel.hs
src/Streamly/Streams/SVar.hs
src/Streamly/Streams/Serial.hs
src/Streamly/Streams/StreamD.hs
src/Streamly/Streams/StreamK.hs

There are still 30 hints for the src tree. One for unnecessary parentheses around a call to `inline`, and the rest for unused LANGUAGE pragmas, to reduce duplication, or for η-reduction.
I didn't do η-reduction when a function didn't have a type signature and had multiple parameters.

ran src through hlint, made most changes; added .hlint.yaml.

---

Changelog.md
src/Streamly/SVar.hs
src/Streamly/Streams/Ahead.hs
src/Streamly/Streams/Async.hs
src/Streamly/Streams/Parallel.hs
src/Streamly/Streams/StreamK.hs
stack-7.10.yaml
stack-8.0.yaml
stack.yaml
test/Main.hs

Currently, the semantics of stateful concurrent tasks is to start with the state from the point where the task is forked but discard any state changes performed in independent threads once they are done. Alternative semantics like merging the state changes or using atomic modifications to state may be implemented in future.
This causes up to 30% regression in async stream generation benchmarks and up to 200% regression in async nested benchmarks. Mostly, due to an additional functional call that cannot be inlined.

Fix monadic state capture and restore for concurrent tasks

---

src/Streamly/Prelude.hs
src/Streamly/Streams/StreamD.hs
streamly.cabal

Two main optimizations in this PR:
1) `mapMaybeM` optimized for composition 
2) use `-fspec-constr-recursive=10` to enable deeper spec-constr optimization for composed ops
Here are the before and after results:
```
100,000 elems(time)
Benchmark                             default(0)(μs)(base) default(1)(%)(-base)
------------------------------------- -------------------- --------------------
serially/mixedX4/take-drop                         2797.43               -86.88
serially/mixedX4/drop-scan                         4850.58               -91.23
serially/filteringX4/dropWhile-false               2799.01               -92.85
serially/mixedX4/filter-drop                        580.90               -94.41
serially/filteringX4/drop-one                       635.97               -94.85 …
```

Optimizations

---

src/Streamly/Tutorial.hs

Fixed the function exposed within the tutorial to pass from Streaming lib to Streamly.

Updated tutorial

---

benchmark/Concurrent.hs
streamly.cabal

Add benchmarks to measure memory usage when different concurrency styles, many threads, buffering for largish streams and streams of streams.

Concurrency benchmarks

---

streamly.cabal

This is a temporary change to not build the network functionality for ghcjs, once the appropriate js ffi is added to the network package we may not need to do this.

Conditionally compile network package for ghcjs.

---

src/Streamly/Streams/StreamD.hs
stack.yaml
streamly.cabal
test/inspection.hs

This is how it looks when the test fails:
```
test/inspection.hs:33:1: test214 does not contain dictionary values failed:
go_sdTh = \ (ds1 [Dmd=<S,1*U>] :: ghc-prim-0.5.3:GHC.Types.SPEC)
[... many more lines stripped --@neongreen]

Add an inspection test for #214

---

src/Streamly/Streams/Instances.hs
src/Streamly/Streams/StreamD.hs

I looked through other rules and as far as I can tell they are safe, these was the only one that needed fixing to run only in Identity.

Fix a bug in zipWithM rule that causes effects to run only once.

---

Changelog.md
README.md
benchmark/FileIO.hs
examples/HandleIO.hs
src/Streamly/FileSystem/FD.hs
src/Streamly/FileSystem/File.hs
src/Streamly/FileSystem/Handle.hs
src/Streamly/Mem/Array.hs
src/Streamly/Mem/Array/Stream.hs
src/Streamly/Mem/Array/Types.hs
src/Streamly/Network/Client.hs
src/Streamly/Network/Socket.hs
src/Streamly/String.hs
streamly.cabal
test/Arrays.hs
test/String.hs

A new module to deal with combinators that work on streams of arrays.
Is that the correct place in module hierarchy? Or are there any other possibilities e.g. `Streamly.Mem.ArrayStream`?

Streamly.Mem.Array.Stream

---

benchmark/FileIO.hs
examples/FileIOExamples.hs
examples/HandleIO.hs
src/Streamly/FileSystem/FD.hs
src/Streamly/FileSystem/File.hs
src/Streamly/FileSystem/Handle.hs
src/Streamly/Network/Client.hs
src/Streamly/Network/Socket.hs

The following functions are renamed in this PR
- readArraysOfUpto -> readArraysOf
- readByChunksUpto -> readInChunksOf
- writeByChunksUpto -> writeInChunksOf
- writeByChunks -> writeInChunksOf (to be consistent with readInChunksOf)
Some functions, not exposed, might still have the old names.

Renaming of read / write apis

---

README.md
bench.sh
benchmark/ArrayOps.hs
benchmark/Chart.hs
benchmark/FileIO.hs
benchmark/Linear.hs
examples/EchoServer.hs
examples/FileSinkServer.hs
examples/FromFileClient.hs
examples/HandleIO.hs
src/Streamly/FileSystem/Handle.hs
src/Streamly/FileSystem/Handle/Internal.hs
src/Streamly/Fold/Types.hs
src/Streamly/Internal.hs
src/Streamly/Memory/Array.hs
src/Streamly/Memory/Array/Types.hs
src/Streamly/Network/Client.hs
src/Streamly/Network/Socket.hs
src/Streamly/Streams/StreamD/Type.hs
src/Streamly/String.hs
streamly.cabal
test/Arrays.hs

The `fileio` `readStream/cat` benchmark seems to have gotten badly affected. Maybe some INLINE issue. Need to investigate.

Implement IO write operations as folds.

---

benchmark/FileIO.hs
examples/HandleIO.hs
src/Streamly/Data/String.hs
src/Streamly/FileSystem/FD.hs
src/Streamly/FileSystem/File.hs
src/Streamly/FileSystem/Handle.hs
src/Streamly/Memory/Array.hs
src/Streamly/Memory/ArrayStream.hs
src/Streamly/Network/Client.hs
src/Streamly/Network/Socket.hs
src/Streamly/Prelude/Internal.hs
streamly.cabal
test/Arrays.hs
test/String.hs

Each container type (e.g. Handle/Socket/File) may have similar nested/stream
level operations. We need a standardized way of naming the combinators related
to streams of containers.  Also, we cannot have a separate module for such
combinators for each container type. Therefore it makes sense to put them in
the same module.

merge the ArrayStream module to Array module itself

---

.travis.yml
benchmark/FileIO.hs
src/Streamly/Benchmark/FileIO/Array.hs
src/Streamly/Benchmark/FileIO/Stream.hs
src/Streamly/Benchmark/Inspection.hs
streamly.cabal

Added two benchmark modules to the library that are enabled by the `benchmark` build flag. These modules build benchmark functions along with inspection tests, these same functions are used by the `fileio` benchmarks. The `fileio` benchmark can now be built only with this flag.

Add inspection testing for fileio benchmarks

---

.travis.yml
Changelog.md
bench.sh
benchmark/FileIO.hs
benchmark/Linear.hs
benchmark/LinearAsync.hs
benchmark/LinearRate.hs
design/inlining.md
docs/Build.md
examples/ControlFlow.hs
src/Streamly/Benchmark/FileIO/Stream.hs
src/Streamly/Benchmark/Prelude.hs
src/Streamly/FileSystem/FD.hs
src/Streamly/FileSystem/File.hs
src/Streamly/FileSystem/Handle.hs
src/Streamly/FileSystem/Handle/Internal.hs
src/Streamly/Internal.hs
src/Streamly/Memory/Array.hs
src/Streamly/Memory/Array/Types.hs
src/Streamly/Memory/ArrayStream.hs
src/Streamly/Network/Client.hs
src/Streamly/Network/Socket.hs
src/Streamly/Prelude/Internal.hs
src/Streamly/Streams/Parallel.hs
src/Streamly/Streams/StreamD.hs
src/Streamly/Streams/StreamD/Type.hs
streamly.cabal
test/Arrays.hs

* Reimplement groupsOf for better fusion
* Use A.writeNUnsafe for better fusion with groupsOf
Now we can use chunksOf/groupsOf to implement arraysOf with equivalent
performance. This commit hides the arraysOf from the Array module and export it
via Streamly.Internal because in one case (writeS) it still is faster. This can
be resolved once GHC issue is resolved. Even though writeS is not an officially
exported API, this case indicates that there may potentially be more such cases
which do not fuse well, so we are keeping this as a backup for such cases for
now.

implement arraysOf in terms of chunksOf

---

src/Streamly/Fold.hs
streamly.cabal

* Use `alterF` to speed up `Map` modification.
* Make `demuxWith` and `demuxWith_` just powerful enough to implement
`demux` and `demux_` without extra mapping. We could actually go
further if we wanted.

Improve demuxing

---

benchmark/NestedUnfold.hs
benchmark/NestedUnfoldOps.hs
src/Streamly/Internal/Data/Unfold.hs
streamly.cabal

Especially add chaining of unfolds (`concat`) and `outerProduct` operations. `outerProduct` is
just the cartesian product of two streams, it is like the concatMap/bind for
streams. In contrast to concatMap, the unfold nested looping operations are
amenable to complete fusion providing us amazing performance equivalent to
linear stream operations.

Add nested unfold operations and benchmarks

---

benchmark/ArrayOps.hs
benchmark/Linear.hs
examples/EchoServer.hs
examples/FileIOExamples.hs
examples/FileSinkServer.hs
examples/FromFileClient.hs
examples/HandleIO.hs
examples/WordClassifier.hs
src/Streamly/Benchmark/FileIO/Array.hs
src/Streamly/Benchmark/FileIO/Stream.hs
src/Streamly/Internal/Prelude.hs
src/Streamly/Prelude.hs
test/Arrays.hs
test/String.hs

* we are using "unfold" for unfolding, runUnfold is longer and sounds a bit
weird. So similar to "unfold" we should use "fold" for folding.
* Another reason is that "runFold" sound ends in "unfold" so can sound
confusing.

rename "runFold" to "fold"

---

benchmark/FileIO.hs
src/Streamly/Benchmark/FileIO/Array.hs
src/Streamly/Benchmark/FileIO/Stream.hs
src/Streamly/Data/String.hs
src/Streamly/Internal/Data/Unfold.hs
src/Streamly/Internal/Memory/ArrayStream.hs
src/Streamly/Internal/Prelude.hs
src/Streamly/Streams/StreamD.hs
src/Streamly/Streams/StreamK.hs

* Rearrange, update benchmarks for words/unwords, lines/unlines
* Add interpose/intercalate/interleaveInfix/interleaveSuffix to Prelude
* Add unfoldWords to Data.String
Use the newly added rotuines to write words/unwords and lines/unlines more
idiomatically and with improved performance.

Add unfoldWords/interpose/intercalate etc.

---

examples/WordCount.hs
src/Streamly/Data/String.hs
src/Streamly/Streams/StreamD.hs
streamly.cabal

1) On utf8 inputs the serial version is around 3x faster than MacOS `wc`
2) It can run parallely on multiple cores providing further speedup (7x faster than serial MacOS `wc` on 4 core macbook pro)
3) Parallel version works efficiently on stdin/streaming input as well
4) Parallel version handles utf8 input correctly (including multi-byte space
chars) and gives the same output as the serial version on all inputs.
5) There may be differences in word/char counts when there are invalid utf8
byte sequences present in the input because of different styles of error
handling.
See notes in examples/WordCount.hs for more details.

Fast, streaming and parallel word counting (wc) program.

---

docs/Build.md
src/Streamly/Streams/StreamD.hs
streamly.cabal

* Use a fast path yield point for ascii encoding
* bump up the spec-constr-recusrive limit
We still need our GHC plugin for full fusion of decode/encode pipeline.

Some tweaks for encodeUtf8 perf

---

docs/Build.md
src/Streamly.hs
src/Streamly/Streams/StreamD.hs
streamly.cabal

People often confuse whether "maxBuffer" and other such combinators apply to
combinators that follow them or to  combinators that precede them.
The examples that wrote can be improved.

Add a pitfall note on concurrency control parameters

---

benchmark/FileIO.hs
examples/FileSinkServer.hs
examples/WordClassifier.hs
examples/WordCount.hs
src/Streamly/Benchmark/FileIO/Array.hs
src/Streamly/Benchmark/FileIO/Stream.hs
src/Streamly/Data/Unicode/Stream.hs
src/Streamly/Internal/Data/Unicode/Char.hs
src/Streamly/Internal/Data/Unicode/Stream.hs
src/Streamly/Internal/Memory/Unicode/Array.hs
streamly.cabal
test/String.hs

We will have at least two modules for unicode string handling APIs
1) `Streamly.Data.Unicode.Stream` - for converting utf8/16/32 encoded Word8 streams to Char streams and vice-versa. It will also have unicode stream segmentation and collation routines ultimately.
2) `Streamly.Data.Unicode.Char` - for Unicode character properties, character transformations etc.
For Storage of unicode strings in memory we can have:
1) `Streamly.Memory.Unicode.Utf8/Utf16LE/Utf16BE/Utf32LE/Utf32BE` etc. these could be newtypes representing arrays containing Utf8/16/32 format strings in memory.

Reorganize Unicode string handling modules

---

examples/EchoServer.hs
examples/FileIOExamples.hs
examples/FromFileClient.hs
examples/HandleIO.hs
examples/WordCount.hs
src/Streamly/Benchmark/FileIO/Array.hs
src/Streamly/Benchmark/FileIO/Stream.hs
src/Streamly/FileSystem/Handle.hs
src/Streamly/Internal/FileSystem/File.hs
src/Streamly/Internal/FileSystem/Handle.hs
src/Streamly/Internal/Network/Inet/TCP.hs
src/Streamly/Internal/Network/Socket.hs
src/Streamly/Memory/Array.hs
src/Streamly/Network/Socket.hs

* Renamed "Array" with a more generic "Chunk", because these APIs may apply to cases where our data structure may not be named "Array" and "Chunk" sounds more high level, not specific to a particular data structure.
* I was confused with `readInChunksOf` etc, made it explicitly `readRequestsOf` to denote that we are referring to the IO request sent to the device or the OS and not to what we are reading.

Rename some IO APIs and update documentation

---

benchmark/Linear.hs
src/Streamly/Benchmark/Prelude.hs
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/SVar.hs
src/Streamly/Internal/Prelude.hs
src/Streamly/Streams/StreamD.hs
src/Streamly/Streams/StreamK.hs

Added `hoist` and `generally`. The latter is a special case of `hoist` to generalize a pure stream to a general monad.
The StreamK code is based on #256 . The original code based on `uncons` required `MonaTrans t` and `Monad (t m)` constraints and was 2x slower (9ms vs 4ms for `length`) compared to the improved version by @pranaysashank .
However, the StreamK code is not being used in the exposed combinators. We are using the `StreamD` version which fuses well and is much faster (33 us for `length`), adding the `hoist` combinators makes no difference at all to `length`.

Hoist and generalizing routines

---

src/Streamly/Streams/StreamK/Type.hs

This can help in signatures with lesser constraints where we use polymorphic
code that requires the stream to be a functor/applicative/semigroup/monoid.
fixes #155

use QuantifiedConstraints on IsStream type class

---

src/Streamly/Internal/Memory/Array.hs
src/Streamly/Internal/Memory/Array/Types.hs
src/Streamly/Internal/Prelude.hs
src/Streamly/Streams/StreamD.hs

Mainly motivated by the fasta benchmark.

Expose some unsafe array primitives and add intersperseSuffixBySpan

---

CONTRIBUTING.md
Changelog.md
bench.sh
design/module-organization.md
design/utf8-decoder.md
examples/ControlFlow.hs
src/Streamly.hs
src/Streamly/Data/Fold.hs
src/Streamly/Internal/Data/Pipe.hs
src/Streamly/Internal/Data/SVar.hs
src/Streamly/Internal/FileSystem/File.hs
src/Streamly/Internal/Prelude.hs
src/Streamly/Prelude.hs
src/Streamly/Streams/Serial.hs
src/Streamly/Streams/StreamD.hs

All changes should be non-semantic.

Fix some easy-to-make typos

---

src/Streamly/Internal/Data/Stream/Serial.hs
src/Streamly/Internal/Prelude.hs

This combinator does not require the MonadAsync constraint, therefore, it can
be used in mondads not based on IO.
fixes #326

Add unfoldrM for serial streams

---

.travis.yml
benchmark/FileIO.hs
benchmark/Linear.hs
benchmark/LinearAsync.hs
benchmark/LinearRate.hs
benchmark/Streamly/Benchmark/FileIO/Array.hs
benchmark/Streamly/Benchmark/FileIO/Stream.hs
benchmark/Streamly/Benchmark/Prelude.hs
cabal.project.ci
streamly.cabal

The modules have been specified to common benchmark properties in the cabal file. They could be moved to individual benchmarks though.

Move Benchmark* from src/ to benchmark/

---

benchmark/Linear.hs
benchmark/Nested.hs
benchmark/NestedOps.hs
benchmark/Streamly/Benchmark/FileIO/Stream.hs
src/Streamly/Internal/Data/Stream/Ahead.hs
src/Streamly/Internal/Data/Stream/Async.hs
src/Streamly/Internal/Data/Stream/Instances.hs
src/Streamly/Internal/Data/Stream/Parallel.hs
src/Streamly/Internal/Data/Stream/Serial.hs
src/Streamly/Internal/Data/Stream/StreamD/Type.hs
src/Streamly/Internal/Data/Stream/StreamK/Type.hs
src/Streamly/Internal/Data/Stream/Zip.hs
src/Streamly/Internal/Prelude.hs
streamly.cabal

Functor instances of various stream types are directly expressed in terms of
StreamD map impl.
Applicative instances now use concatMap instead of using "ap" from Monad.
Rewrite rules to specialize unfoldrM to WSerial and ZipSerial as well so
that it performs well for those. This was causing benchmarks for these
to be much slower beacause of unfoldrM used in the benchmarks being
slow.  For this, I had to move the zipWith* impls into the Zip module so
that we can import the ZipSerial type in Prelude.

improve perf of functor and applicative instances

---

streamly.cabal

- Earlier the internal benchmark components have directly used streamly modules, but since we now expose almost all internal modules we can now depend on the library instead.
- This PR exposes StreamDK modules, one drawback is that now these modules would show up on the streamly hackage landing page.

Depend on streamly library for internal benchmarks.

---

Changelog.md
src/Streamly/Internal/Data/Stream/Async.hs

We run the stream in a worker thread using captured monadic state from the parent thread. The call to mrun caused memory to stack up because it is called again and again and never returns. We need this call only once when a stream is picked for execution from the work queue. We do not need to call mrun on every yield. The call on yield is removed by this commit.
Fixes #346

Fix space leak in async combinator

---

.gitignore
benchmark/BaseStreams.hs
benchmark/Linear.hs
benchmark/StreamDOps.hs
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Data/Stream/StreamK.hs
src/Streamly/Internal/Prelude.hs
streamly.cabal
test/Streamly/Test/Internal/Data/Fold.hs

Simple one-line combinators.
`iterate`
`iterateM`
`drainN`
`drainWhile`
`rollingHashFirstN`
The changes were small, hence used a single PR.

Simple combinators

---

benchmark/Common.hs
benchmark/Linear.hs
benchmark/LinearAsync.hs
benchmark/LinearRate.hs
benchmark/Nested.hs
benchmark/NestedConcurrent.hs
benchmark/NestedOps.hs
benchmark/Streamly/Benchmark/Prelude.hs
streamly.cabal

* This includes linear, linear-async, linear-rate
* Modules removed: linear-long, linear-async-long
* CPP options removed: -DLINEAR_ASYNC
TODO:
NOTE: Other benchmarks should be made/modified in the same fashion, but that can be done in the later stage when variable length is needed. This PR only aims to get rid of the current cpp-options that define the stream length.

Remove cpp-options that control length in linear*

---

MAINTAINING.md
bench.sh
benchmark/Chart.hs
benchmark/Common.hs
benchmark/NestedUnfold.hs
benchmark/NestedUnfoldOps.hs
streamly.cabal

* Fix `--stream-size` passing to child process for gauge `--measure-with` option to work correctly
* Support command line stream-size option for nested-unfold benchmark as well
* Support `--long` option in `bench.sh` to conveniently run large stream size (10 million elements) benchmarks before releasing.

large stream size benchmarks

---

benchmark/Linear.hs
benchmark/LinearAsync.hs
benchmark/Nested.hs
benchmark/NestedConcurrent.hs
benchmark/NestedOps.hs
benchmark/Parallel.hs
benchmark/Streamly/Benchmark/Prelude.hs
streamly.cabal

So that we can run different benchmark groups with different heap size restrictions. Especially we want to enforce that streaming benchmarks run in constant memory.
See the commit messages for more details.

Group benchmarks based on memory and cpu costs

---

benchmark/FileIO.hs
benchmark/Streamly/Benchmark/FileIO/Array.hs
benchmark/Streamly/Benchmark/FileIO/Stream.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Data/Unfold.hs
src/Streamly/Internal/Prelude.hs

The "after", "finally" and "bracket" combinators did not run the "cleanup"
handler in case the stream is lazily partially evaluated e.g. using the lazy
right fold (foldrM), "Streamly.Prelude.head" is an example of such a fold.
Since we run the cleanup action when the stream Stops, the action won't be run
if the stream is not fully drained.
In the new implementation, we use a GC hook to run the cleanup action in case
the stream got garbage collected even before finishing. This will take care of
the lazy right fold cases mentioned above.

Add exception handling combinators with guaranteed cleanup

---

benchmark/LinearAsync.hs
benchmark/Streamly/Benchmark/Prelude.hs

Do not use "tail" in zip benchmarks otherwise the tail perf can impact these
benchmarks. Also it makes them consistent with other such benchmarks.
Use half the stream size for each side of zip so that we effectively
create a stream of size similar to other linear benchmarks.

normalize zip benches, add mergeAsyncByM benchmark

---

benchmark/Streamly/Benchmark/Prelude.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Prelude.hs

The predicate provides more power to the combinator by allowing you to count
only certain elements in the stream and filter out others. This is efficient
compared to an async tap followed by a filter and fold as here filtering is
done on the source.

Add a predicate to pollCounts

---

benchmark/Linear.hs
docs/Build.md
src/Streamly/Internal/Data/Stream/SVar.hs
streamly.cabal

See GHC ticket https://gitlab.haskell.org/ghc/ghc/issues/17745

Add the -fdicts-strict flag to avoid memory leaks

---

.circleci/config.yml
.github/workflows/haskell.yml
.travis.yml
Changelog.md
appveyor.yml
docs/Build.md
src/Streamly/Internal/Data/Stream/StreamD/Type.hs
src/Streamly/Internal/Fusion.hs
stack.yaml
streamly.cabal

Use `fusion-plugin` package when `fusion-plugin` build flag is enabled. The plugin is used for benchmarks as well as tests.

Use fusion-plugin package

---

benchmark/Linear.hs
benchmark/Streamly/Benchmark/Prelude.hs
src/Streamly/Internal/BaseCompat.hs
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Stream/Instances.hs
src/Streamly/Internal/Data/Stream/Prelude.hs
src/Streamly/Internal/Data/Stream/Serial.hs
src/Streamly/Internal/Data/Stream/Zip.hs
src/Streamly/Internal/Data/Strict.hs
src/Streamly/Internal/Prelude.hs
streamly.cabal

Add benchmarks for `Foldable` and `Traversable` instances and reimplement `Foldable` instance for better space and time performance.

Foldable performance

---

benchmark/lib/Streamly/Benchmark/Prelude.hs
streamly.cabal

Solves a few points mentioned in #255

Keep signature/pragma and definitions for each benchmark together

---

benchmark/Streamly/Benchmark/Prelude/Serial/O_1_Space.hs
benchmark/Streamly/Benchmark/Prelude/Serial/O_n_Heap.hs
benchmark/lib/Streamly/Benchmark/Data/Fold.hs
benchmark/lib/Streamly/Benchmark/Prelude.hs
benchmark/streamly-benchmarks.cabal
streamly.cabal

Solves a few points mentioned in #255

Seperate folds from Prelude in benchmarks.

---

src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Data/Unfold.hs

Without this change, there are points (between "bef" and registration of "aft") at which async exceptions can cause resource leaks.
A similar thing is done here: https://github.com/snoyberg/conduit/blob/resourcet-1.2.3/resourcet/Control/Monad/Trans/Resource.hs#L119

Mask async exceptions in the "bracketIO" functions.

---

.hlint.yaml
src/Streamly/Internal/FileSystem/Dir.hs
src/Streamly/Internal/FileSystem/File.hs
src/Streamly/Internal/FileSystem/Handle.hs
src/Streamly/Internal/Memory/Array.hs
src/Streamly/Internal/Memory/Array/Types.hs
src/Streamly/Internal/Memory/ArrayStream.hs

For #406 
For added context, as mentioned on gitter channel, the benchmark currently fails
```
Running benchmark fileio ...
creating input file benchmark/scratch/in-100MB.txt
dd: warning: partial read (116 bytes); suggest iflag=fullblock
0+3200 records in
0+3200 records out
19507 bytes (20 kB, 19 KiB) copied, 10433.4 s, 0.0 kB/s
readArray/last
iters                194
time                 6.091 fileio: <stdout>: hPutChar: invalid argument (invalid character)
Error: Benchmarking failed
```
The test takes quite a bit of time even on master.
Signed-off-by: Sanchayan Maity <maitysanchayan@gmail.com>

Streamly: Internal: FileSystem: Cleanup hlint warnings

---

bench.sh
benchmark/Chart.hs
benchmark/streamly-benchmarks.cabal

1. Removed rts options at compile time for fold benchmark.
2. Added fold-o-1-space and fold-o-1-heap benchmark to bench.sh
3. Added fold-o-1-space and fold-o-1-heap to bench.sh

Multiple changes corresponding to the fold benchmark.

---

benchmark/Chart.hs
benchmark/Streamly/Benchmark/Data/Parser.hs
benchmark/Streamly/Benchmark/Data/ParserD.hs
benchmark/Streamly/Benchmark/Data/ParserK.hs
benchmark/Streamly/Benchmark/FileIO/Stream.hs
benchmark/streamly-benchmarks.cabal
src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Parser/ParserD.hs
src/Streamly/Internal/Data/Parser/ParserD/Tee.hs
src/Streamly/Internal/Data/Parser/ParserD/Types.hs
src/Streamly/Internal/Data/Parser/ParserK/Types.hs
src/Streamly/Internal/Data/ParserK/Types.hs
src/Streamly/Internal/Data/Stream/Prelude.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Data/Zipper.hs
src/Streamly/Internal/Prelude.hs
streamly.cabal

CPS is good at scalable applicative/monad/alternative operations and direct style is good at stream fusion providing better performance. We use both via rewrite rules depending on the situation.

Add CPS parser, use both CPS and direct style parsers

---

design/unicode.md

We have quite fast stream based [utf8 decoding](https://github.com/composewell/streamly/blob/500d187b8fb5b6b1bc424725dd179650fb41c49c/src/Streamly/Internal/Data/Unicode/Stream.hs#L253) in streamly, we can translate the unicode normalization from `unicode-transform` to stream based normalization in `streamly` in the same way.
Also we can perhaps encode the [decodeTable](https://github.com/composewell/streamly/blob/500d187b8fb5b6b1bc424725dd179650fb41c49c/src/Streamly/Internal/Data/Unicode/Stream.hs#L146) as a static string instead of generating an array at runtime. Won't make any difference to perf but would be simpler I guess.
cc @Bodigrim

Add a document about unicode text processing plans

---

benchmark/FileIO.hs
benchmark/Streamly/Benchmark/Data/Fold.hs
benchmark/Streamly/Benchmark/Data/Parser.hs
benchmark/Streamly/Benchmark/Data/ParserD.hs
benchmark/Streamly/Benchmark/FileIO/Stream.hs
benchmark/streamly-benchmarks.cabal
src/Streamly/Data/Fold.hs
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Prelude.hs
src/Streamly/Prelude.hs

Iterate parsers on a stream such that the next parser depends on the previous parser, generating an output stream from the intermediate parse results.

Add concatParse for chained parsing

---

benchmark/lib/Streamly/Benchmark/Prelude.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Data/Time/Units.hs
src/Streamly/Internal/Prelude.hs

add: times, relTimes, timestamped
unimplemented skeletons: durations, ticks, timeout
Changes to the original currentTime combinator: remove delay from the first
event, cap the granularity to 1 ms to guarantee reasonable cpu usage.

Add some time related combinators

---

src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Parser/ParserD.hs

- Fix `sliceSepByMax`
- Add examples for `Parser.eqBy`

Fix sliceSepByMax

---

.hlint.ignore
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Pipe.hs
src/Streamly/Internal/Data/Pipe/Types.hs
src/Streamly/Internal/Data/Prim/Array.hs
src/Streamly/Internal/Data/SVar.hs
src/Streamly/Internal/Data/Sink/Types.hs
src/Streamly/Internal/Data/SmallArray.hs
src/Streamly/Internal/Data/SmallArray/Types.hs
src/Streamly/Internal/Data/Time/Units.hs

Another round of clean ups for #406 
Have not removed `SmallArray/Types.hs` and `Pipe/Types.hs` from `.hlint.ignore` as they still need some clean up which I am not sure if they should be made or silenced. Will come back to it in the end I guess.
Signed-off-by: Sanchayan Maity <maitysanchayan@gmail.com>

Streamly: Internal: Data: Clean up hlint warnings

---

bin/bench-exec-one.sh
src/Streamly/Internal/Data/Parser/ParserD.hs
src/Streamly/Internal/Data/Parser/ParserD/Tee.hs
src/Streamly/Internal/Data/Parser/ParserD/Types.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
src/Streamly/Internal/Data/Zipper.hs

Yield 0: now means a partial result is available
Yield n: means a partial result is available, and we need to backtrack by n
elements.
Benchmark comparison with fusion-plugin on:
```
Data.Parser(time)
Benchmark                           default(0)(μs) default(1) - default(0)(%)
----------------------------------- -------------- --------------------------
Data.Parser/o-1-space/shortest               62.63                     +50.24
Data.Parser/o-1-space/splitApAfter          757.14                      +3.92
Data.Parser/o-1-space/tee                    93.87                      +3.60
Data.Parser/o-n-heap/someAlt              30854.19                      +2.53
Data.Parser/o-1-space/splitApBefore         756.69                      +1.86
Data.Parser/o-n-heap/sequenceA            18230.55 …
```

Combine Yield and YieldB constructors

---

.hlint.ignore
Changelog.md
benchmark/Streamly/Benchmark/FileIO/Stream.hs
benchmark/Streamly/Benchmark/Memory/ArrayOps.hs
benchmark/Streamly/Benchmark/Prelude/Serial.hs
examples/WordClassifier.hs
examples/WordCount.hs
src/Streamly/Internal/Data/Array.hs
src/Streamly/Internal/Data/Prim/Array.hs
src/Streamly/Internal/Data/SmallArray.hs
src/Streamly/Internal/Data/Stream/StreamD/Type.hs
src/Streamly/Internal/Data/Stream/StreamK.hs
src/Streamly/Internal/Memory/Array/Types.hs
src/Streamly/Internal/Memory/ArrayStream.hs
src/Streamly/Internal/Prelude.hs
test/Main.hs
test/Prop.hs

It feels a bit awkward to use this new fold signature. Maybe it'd be
better if we provide functions with both the fold signatures.

Change the signature of foldlM' to use a monadic accumulator.

---

CONTRIBUTING.md
benchmark/Chart.hs

"allocated" is much more stable for regression comparisons as it stays the same
whereas "time" varies based on various factors like cpu frequency, other things
running on the computer, context switches etc.
bytesCopied is a measure of long lived data being retained across GCs, which is
also a good measure of performance.

Add "allocated" and "bytesCopied" fields

---

src/Streamly/Internal/Data/List.hs
src/Streamly/Internal/Data/Prim/Array/Types.hs
src/Streamly/Internal/Data/SmallArray/Types.hs
src/Streamly/Internal/Data/Stream/Serial.hs
src/Streamly/Internal/Data/Stream/Zip.hs
src/Streamly/Internal/Memory/Array/Types.hs
src/Streamly/Memory/Malloc.hs
streamly.cabal
test/Prop.hs
test/PureStreams.hs

MonoLocalBinds enabled by TypeFamilies causes performance regressions
see #567, however we can enable TypeFamilies without it.

Enable TypeFamilies extension with NoMonoLocalBinds

---

src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Parser/ParserD.hs
test/Streamly/Test/Internal/Data/Parser.hs
test/Streamly/Test/Internal/Data/Parser/ParserD.hs

- `take` and `takeEQ` now work when the count is 0.
- `sliceSepByMax` behaviour is now more in line with what the
documentaton says in `Streamly.Internal.Data.Parser`.
- TODO: Tests need to be fixed, a bit unclear how best to proceed with them.

Fix take, takeEQ, sliceSepByMax.

---

Changelog.md
src/Streamly/Internal/Data/Parser/ParserK/Types.hs
src/Streamly/Internal/Data/Stream/StreamK/Type.hs
src/Streamly/Internal/Prelude.hs

- Do the same with `bindWith`, `concatMapBy`, `concatMapIterateWith`,
`concatMapTreeWith`.
- `concatMapLoopWith`,`concatMapTreeYieldLeavesWith` are not updated
in the same way as they necessarily need the combining function to be
polymorphic.
- Update Changelog to reflect this change.

Updated type signature of `concatMapWith` to remove explicit forall.

---

src/Streamly/Data/Unicode/Stream.hs
src/Streamly/Internal/Data/Unicode/Stream.hs

There is not much performance penalty for using the lenient variant instead of the normal one. Maybe we should use the same implementation for both the functions.

Add encodeUtf8Lax.

---

src/Streamly/Internal/Foreign/Malloc.hs
src/Streamly/Internal/Memory/Mutable/Array/Types.hs
src/Streamly/Memory/Malloc.hs
streamly.cabal

Provide a build flag to use C malloc for pinned arrays instead of using GHC malloc

---

Changelog.md
benchmark/Streamly/Benchmark/FileSystem/Handle/Read.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/ReadWrite.hs
examples/FileSinkServer.hs
examples/WordCount.hs
src/Streamly/Data/Unicode/Stream.hs
src/Streamly/Internal/FileSystem/Event/Darwin.hs
src/Streamly/Internal/FileSystem/Event/Linux.hs
src/Streamly/Internal/Unicode/Stream.hs
src/Streamly/Unicode/Stream.hs
test/Streamly/Test/FileSystem/Event.hs
test/String.hs

Add `encodeUtf8_`, `encodeLatin1_`, `encodeUtf8'`, `encodeLatin1'`, `decodeUtf8_`, `decodeUtf8'`, `decodeUtf8Arrays'`, `decodeUtf8Arrays_`. 
See #658. 
Closes #658

New encoding/decoding routines.

---

bench.sh

Use namespaced components when passing to cabal in bench.sh.

---

src/Streamly/Tutorial.hs

There are two commits: the first one is a general clean up of the streaming interop examples in the tutorial; the second one adds `fromConduit`. This new function is implemented in terms of conduit’s `unconsM`, which is _almost_ merged now (snoyberg/conduit#451).

Add fromConduit to Tutorial

---

src/Streamly/Internal/FileSystem/Event/Darwin.hs
streamly.cabal

Otherwise it is always built when we build the library.

Put fs event executable under manual-tests flag

---

src/Streamly/Internal/Data/Array/Storable/Foreign.hs
src/Streamly/Internal/Data/Array/Storable/Foreign/Mut/Types.hs
src/Streamly/Internal/Data/Array/Storable/Foreign/Types.hs
test/MaxRate.hs

```
#ifdef DEVBUILD
Storable a =>
#endif
```
Should be added to almost all the functions in `Foreign.Array`

Configure storable array to work properly when building with "-f dev"

---

Changelog.md
benchmark/Streamly/Benchmark/Prelude/Serial.hs
src/Streamly/Internal/Data/Stream/IsStream.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
test/Streamly/Test/Prelude/Common.hs
test/Streamly/Test/Prelude/Fold.hs

The following functions are updated: scanlM, scanlM', postscanlM, postscanlM', prescanlM'.
Closes #150.

Use monadic seed in monadic scanning combinators.

---

src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Parser/ParserK/Types.hs

ParserD yieldM requires an additional input to yield a value, ParserD needs
to be fixed in general to avoid this issue.

Use yieldM from ParserK

---

benchmark/Streamly/Benchmark/FileSystem/Handle/ReadWrite.hs

We were reading input from a binary file trying to decode it as Char
leading to an invalid byte sequence error.

Fix "Invalid byte" on file read

---

src/Streamly/Internal/Data/Stream/StreamD.hs

1. Make the parser state strict so that it can fuse.
2. Use special paths for "Continue 0" and "Done 0" cases
Overall improvement from 440 us (6GB allocations) to 175 us (22 MB
allocations).

Improve performance of parseMany

---

benchmark/Streamly/Benchmark/FileSystem/Handle.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/Common.hs

Specifying the input file via an environment variable was broken.

Specify benchmark input file via env var

---

default.nix
streamly.cabal

It depends on a fork of nixpkgs which adds a minor change to `shellFor` so that it honors the benchmark dependencies.

Add default.nix for nix shell/build

---

benchmark/Streamly/Benchmark/Data/Array.hs
benchmark/Streamly/Benchmark/Data/ArrayOps.hs
benchmark/Streamly/Benchmark/Data/Unfold.hs
src/Streamly/Internal/Data/Unfold.hs
test/Streamly/Test/Data/Unfold.hs

Commit 1 closes #734 
Commit 2 fixes a silent bug which was the result of an unused CPP idenifier

Issue solving & bug fixing

---

benchmark/Streamly/Benchmark/FileSystem/Handle/Read.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/ReadWrite.hs
benchmark/Streamly/Benchmark/Prelude/Ahead.hs
benchmark/Streamly/Benchmark/Prelude/Async.hs
benchmark/Streamly/Benchmark/Prelude/Parallel.hs
benchmark/Streamly/Benchmark/Prelude/Rate.hs
benchmark/Streamly/Benchmark/Prelude/Serial.hs
benchmark/Streamly/Benchmark/Prelude/WAsync.hs
benchmark/Streamly/Benchmark/Prelude/ZipAsync.hs
benchmark/Streamly/Benchmark/Prelude/ZipSerial.hs
benchmark/lib/Streamly/Benchmark/Prelude.hs

- ~[ ] once (Depracated)~
- ~[ ] each (Depracated)~
- ~[ ] scanx (Depracated)~
- ~[ ] foldx (Depracated)~
- ~[ ] foldxM (Depracated)~
- ~[ ] foldr1 (Depracated)~
- ~[ ] runStream (Depracated)~
- ~[ ] runN (Depracated)~
- ~[ ] runWhile (Depracated)~
- ~[ ] fromHandle (Depracated)~
- ~[ ] toHandle (Depracated)~
The test suite is named internal, it should be renamed to just
Data.Fold.
test-suite is named array-test, should be renamed.
- ~[ ] decodeLatin1~
- ~[ ] decodeUtf8~
- ~[ ] encodeLatin1~
- ~[ ] encodeUtf8~
- ~[ ] decodeUtf8Lax~
- ~[ ] encodeLatin1Lax~
- ~[ ] encodeUtf8Lax~
- ~[ ] A.fromListN~
- ~[ ] A.fromList~
- ~[ ] A.toList~
- ~[ ] A.read~
- ~[ ] A.length~

Benchmarks for exposed

---

benchmark/Streamly/Benchmark/FileSystem/Handle/ReadWrite.hs

I think we should start using `fusion-plugin` flag along with `inspection` flag. We can have more inspection tests passing that way.

Enable inspection tests for interposeSuffix bench

---

test/Streamly/Test/Prelude/Ahead.hs
test/Streamly/Test/Prelude/Async.hs
test/Streamly/Test/Prelude/Common.hs
test/Streamly/Test/Prelude/Parallel.hs
test/Streamly/Test/Prelude/Serial.hs
test/Streamly/Test/Prelude/WAsync.hs
test/Streamly/Test/Prelude/WSerial.hs

Added basic tests for 
- cons, consM, (.:), (|:)
- yield, yieldM, repeat, repeatM
- enumerate, enumerateTo
- unfoldr
- fromListM
- drainWhile
- findM
- eqBy, cmpBy
- mapM_, trace
- postscanl', postscanlM'
- mapMaybeM
- dropWhileM
- groups, groupsByRolling
- zipAsyncWith
- concatMapM, concatUnfold
- before, after, bracket, onException, finally, handle

Add tests for operations in Streamly.Prelude.

---

src/Streamly/Internal/Data/Fold/Types.hs

If the fold is used for scan, we will end up killing the thread
immediately. Kill it when the fold is done.
We are still not killing the thread if the fold is GCed, but it anyway
go away on timeout.

Do not kill thread on extract

---

benchmark/Streamly/Benchmark/Data/Fold.hs
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Fold/Types.hs
src/Streamly/Internal/Data/Stream/StreamD.hs
streamly.cabal
test/Streamly/Test/Common.hs
test/Streamly/Test/Data/Fold.hs

Data.Fold.Types:
* Remove takeSepBy:  This function does not do what the name. Also,
`takeSepBy p` is the same as (sliceSepBy (not . p)). We can just remove
this in favor of sliceSepBy.
Data.Fold:
* Reorganize exports
* Add some skeleton/unimplemented combinators.
* Add/update haddock documentation
* Add sliceSepByMax fold - It was in parsers but it can be implemented
as a fold.
* Rename drainSepBy to drainWhile
* Rename sliceSepWith to sliceEndWith
* Remove distribute_ as it can be implemented using distribute and has
not perf advantage.
* Remove demuxWithDefault_ and implement demuxDefaultWith instead, which
does not discard the results. Discarding results has no perf
advantage.
* Implement demuxWith in terms of demuxDefaultWith, it has no perf
advantage over the latter.
* Remove …

Review/update docs, combinators in Fold module

---

benchmark/Streamly/Benchmark/Data/Parser.hs
benchmark/Streamly/Benchmark/Data/Parser/ParserD.hs
src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Parser/ParserD.hs
test/Streamly/Test/Data/Parser.hs
test/Streamly/Test/Data/Parser/ParserD.hs

Regressions:
```
Prelude.Serial/o-1-space/grouping/groupsByEq                                          65.92                   +2516.15
Prelude.Serial/o-1-space/grouping/groups                                           34683.66                    +140.63
```
This benchmark is weird. `groupsByEq` and `groups` is the same I believe. `groups = groupsBy (==)`

Implement Data.Parser.ParserD.groupBy

---

benchmark/Streamly/Benchmark/Data/Parser.hs
benchmark/Streamly/Benchmark/Data/Parser/ParserD.hs
src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Parser/ParserD.hs
test/Streamly/Test/Data/Parser.hs
test/Streamly/Test/Data/Parser/ParserD.hs

- Modify Data.Parser.wordBy accordingly
- Add tests for both
- Add benchmarks for both
This requires `fusion-plugin`
```
benchmarked Data.Parser.ParserD/o-1-space/wordBy
time                 65.46 μs   (64.92 μs .. 65.92 μs)
1.000 R²   (0.999 R² .. 1.000 R²)
mean                 65.82 μs   (65.47 μs .. 66.22 μs)
std dev              1.856 μs   (1.475 μs .. 2.670 μs)
variance introduced by outliers: 22% (moderately inflated)
benchmarked Data.Parser/o-1-space/wordBy
time                 64.97 μs   (64.54 μs .. 65.34 μs)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 66.02 μs   (65.67 μs .. 66.49 μs)
std dev              1.967 μs   (1.637 μs .. 2.780 μs)
variance introduced by outliers: 24% (moderately inflated)
```

Implement Data.Parser.ParserD.wordBy

---

.hlint.yaml
benchmark/Streamly/Benchmark/Data/Fold.hs
benchmark/Streamly/Benchmark/Data/Parser.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/Read.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/ReadWrite.hs
benchmark/Streamly/Benchmark/Prelude/Serial/Transformation2.hs
benchmark/Streamly/Benchmark/Unicode/Stream.hs
src/Streamly/Data/Fold.hs
src/Streamly/Internal/Data/Array/Storable/Foreign/Types.hs
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Fold/Types.hs
src/Streamly/Internal/Data/Stream/IsStream/Eliminate.hs
src/Streamly/Internal/Data/Stream/IsStream/Nesting.hs
src/Streamly/Internal/FileSystem/Dir.hs
src/Streamly/Internal/FileSystem/File.hs
src/Streamly/Internal/FileSystem/Handle.hs
src/Streamly/Internal/Memory/ArrayStream.hs
src/Streamly/Internal/Network/Inet/TCP.hs
src/Streamly/Internal/Network/Socket.hs
test/Streamly/Test/Data/Fold.hs
test/Streamly/Test/Data/Parser.hs
test/Streamly/Test/Data/Parser/ParserD.hs

Fold.ltake -> Fold.takeLE
Fold.lfilter -> Fold.filter
Fold.lfilterM -> Fold.filterM
Fold.lmap -> Fold.map
Fold.lchunksOf2 -> Fold.chunksOf2
Fold.lchunksOf -> Fold.chunksOf
Fold.lsessionsOf -> Fold.intervalsOf

Remove the prefix *l* in a few functions of Fold

---

benchmark/Streamly/Benchmark/Data/Parser/ParserD.hs

Rename splitWith benchmark

---

src/Streamly/Internal/Data/Stream/IsStream/Generate.hs

Add how to implement it using enumerateFrom. We can ultimately remove it and recommend using enumerate and map instead.

Update doc of fromIndices

---

.github/workflows/haskell.yml
cabal.project.ci
test/streamly-tests.cabal

We may want to use the -Werror build locally but fusion-plugin takes too
much time to build, so separate the two.

Allow -Werror without inspection/fusion-plugin

---

src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Fold/Types.hs
src/Streamly/Internal/Data/Parser.hs
src/Streamly/Internal/Data/Parser/ParserD/Types.hs
src/Streamly/Internal/Data/Stream/IsStream/Transform.hs
src/Streamly/Internal/Data/Stream/StreamD/Nesting.hs
src/Streamly/Internal/Data/Stream/StreamD/Transform.hs

The unimplemented function `zipWithM` needs to be implemented for this to work.
Combinators like `tapOffsetEvery` can be expressed using `sampleFromThen`.

Sampling support for folds

---

src/Streamly/Internal/Data/Time/Clock.hs

The "undefined" somehow gets evaluated even though it is overwritten
immediately. The benchmarks crash due to this.

Use 0 to initialize IORef instead of undefined

---

bin/bench.sh
bin/build-lib.sh
bin/test.sh

We could use `--with-compiler` in `--cabal-build-options` but we need to find the benchmark/test executable under dist-newstyle based on the compiler version, so we need to know the executable in the shell script.

Add support for --with-compiler

---

benchmark/Streamly/Benchmark/FileSystem/Handle/Read.hs
benchmark/Streamly/Benchmark/FileSystem/Handle/ReadWrite.hs
src/Streamly/Internal/Data/Stream/IsStream/Nesting.hs
src/Streamly/Internal/Data/Stream/StreamD/Type.hs

foldMany1 is the default foldMany now. foldMany is renamed to
foldManyPost which is of limited use to split in an infix manner.

Rename foldMany and foldMany1

---

benchmark/Streamly/Benchmark/Data/Parser/ParserD.hs
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Parser/ParserD.hs
src/Streamly/Internal/Data/Stream/StreamD/Nesting.hs

Simple fixes + additional benchmarks
```
benchmarked Data.Parser.ParserD/o-1-space/parseMany
time                 87.56 μs   (87.24 μs .. 87.92 μs)
1.000 R²   (0.999 R² .. 1.000 R²)
mean                 88.19 μs   (87.60 μs .. 88.82 μs)
std dev              2.778 μs   (2.234 μs .. 3.433 μs)
variance introduced by outliers: 24% (moderately inflated)
benchmarked Data.Parser.ParserD/o-1-space/parseMany groupBy
time                 76.02 μs   (75.44 μs .. 76.73 μs)
1.000 R²   (0.999 R² .. 1.000 R²)
mean                 76.30 μs   (76.02 μs .. 76.61 μs)
std dev              1.493 μs   (1.279 μs .. 1.735 μs)
variance introduced by outliers: 12% (moderately inflated)
benchmarked Data.Parser.ParserD/o-1-space/parseMany groupRollingBy
time                 88.39 μs   (87.98 μs .. 88.75 μs)
1.000 R² …
```

Misc tasks

---

bin/ghc.sh
streamly.cabal

With all the extensions used in streamly, optimization options and
ddump-simpl options.
This is useful for compiling standalone files, when inspecting core for
perf issues.  I wish cabal could invoke ghc with environment from the
cabal file. Can it?

Add a ghc wrapper to invoke ghc on individual files

---

benchmark/Streamly/Benchmark/Prelude/Serial/Transformation2.hs
src/Streamly/Internal/Data/Stream/IsStream/Common.hs
src/Streamly/Internal/Data/Stream/IsStream/Nesting.hs
src/Streamly/Internal/Data/Stream/IsStream/Top.hs
src/Streamly/Internal/Data/Stream/StreamK.hs
src/Streamly/Internal/Data/Stream/StreamK/Type.hs

sortBy is 10x slower than lists, but it could be concurrent. It would be interesting to see how the StreamD implementation of this performs.

Implement concatPairswith/sortBy

---

benchmark/Streamly/Benchmark/Data/Unfold.hs
src/Streamly/Internal/Data/Unfold.hs

Before: not finishing in reasonable time
After: 686 us (similar to fromStream)

Fix fromStreamD performance

---

.github/workflows/haskell.yml
benchmark/streamly-benchmarks.cabal
bin/bench-exec-one.sh
docs/Build.md
src/Streamly/Internal/FileSystem/FD.hs
streamly.cabal
test/lib/Streamly/Test/Prelude/Common.hs

* Still needs `--allow-newer`
* For benchmarks needs - `basement` to be fixed (for gauge), fusion-plugin fixes

Fixes for GHC 9.0 support

---

benchmark/Streamly/Benchmark/Data/Fold.hs
benchmark/Streamly/Benchmark/Prelude/Serial/Split.hs
benchmark/streamly-benchmarks.cabal
src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Fold/Types.hs
src/Streamly/Internal/Data/Stream/IsStream/Nesting.hs
src/Streamly/Internal/FileSystem/Event/Linux.hs
test/Streamly/Test/Data/Fold.hs
test/Streamly/Test/Data/Parser.hs
test/Streamly/Test/Data/Parser/ParserD.hs

This commit has no functional change, only renaming and doc edits.
I have changed `Fold.map` back to Fold.lmap to avoid confusion with `fmap`. This is the only deviation from the names of the APIs in Stream module. It probably makes sense to distinguish names explicitly when we have the same operation as covariant as well as contravariant.

Rename some fold combinators

---

benchmark/Streamly/Benchmark/Prelude/Serial/Transformation2.hs
src/Streamly/Internal/Data/Stream/IsStream/Nesting.hs
src/Streamly/Internal/Data/Stream/StreamD/Nesting.hs
test/Streamly/Test/Prelude/Serial.hs

Benchmarks,
```
benchmarked Data.Fold/o-1-space/nesting/foldIterateM (take 1)
time                 115.4 μs   (114.6 μs .. 116.4 μs)
1.000 R²   (0.999 R² .. 1.000 R²)
mean                 116.8 μs   (116.2 μs .. 117.3 μs)
std dev              2.446 μs   (2.150 μs .. 2.918 μs)
variance introduced by outliers: 12% (moderately inflated)
benchmarked Data.Fold/o-1-space/nesting/foldIterateM (take all)
time                 817.1 μs   (812.2 μs .. 821.7 μs)
1.000 R²   (0.999 R² .. 1.000 R²)
mean                 816.6 μs   (813.0 μs .. 820.2 μs)
std dev              12.36 μs   (10.22 μs .. 15.09 μs)
```
These benchmarks look incorrect,
1. I expected `foldIterateM (take 1)` to be worse compared to `foldIterateM (take all)`
2. In contrast `parseIterate` is much worse. I expected them to be almost …

Implement foldIterate

---

src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Fold/Types.hs

mkfoldr/mkfoldl are better names as the signature directly correspond to `foldl` and `foldr`. We should remove `mkAccum*`. I have kept the names as `mkFoldl` and `mkFoldr` but I like `mkfoldl` and `mkfoldr` etc. more.

Add left and right fold constructors

---

benchmark/Streamly/Benchmark/Unicode/Stream.hs
src/Streamly/Internal/Data/Fold/Type.hs
test/Streamly/Test/Data/Fold.hs

```
benchmarked Data.Fold/o-1-space/composition/many drain (take 1)
time                 51.75 μs   (51.59 μs .. 51.96 μs)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 51.94 μs   (51.66 μs .. 52.32 μs)
std dev              1.562 μs   (1.224 μs .. 1.998 μs)
variance introduced by outliers: 24% (moderately inflated)
```

Make Fold.many consistent with foldMany

---

benchmark/Streamly/Benchmark/Prelude/Serial/Transformation1.hs
src/Streamly/Internal/Data/Stream/IsStream/Eliminate.hs
src/Streamly/Internal/Data/Stream/IsStream/Transform.hs

Primary motivation for renaming takeEnd was to avoid confusion with
takeEndBy but I like the new name takeLast irrespective of that.

Rename stream transformation some APIs

---

src/Streamly/Internal/Data/Stream/IsStream.hs
src/Streamly/Internal/Data/Stream/IsStream/Common.hs
src/Streamly/Internal/Data/Stream/IsStream/Expand.hs
src/Streamly/Internal/Data/Stream/IsStream/Reduce.hs
src/Streamly/Internal/Data/Stream/IsStream/Top.hs
src/Streamly/Internal/Data/Stream/Prelude.hs
streamly.cabal

Sorts out the mess of combinators in the Nested module.
Resurrecting #982 which was closed due to deletion of fold-docs branch.

Split IsStream.Nesting into Expand and Reduce

---

src/Streamly/Internal/Data/Fold/Type.hs

Lazy "initial" in the previous runStep impl lead to writing to handle
after it was closed.

Make runStep eager

---

bin/bench.sh
default.nix

We can always use the chart executable built by any compiler version.
Sometimes the chart executable is not buildable by newer compiler
versions, in that case we can build it using another compiler and use
that.

Add a hack to find "chart" executable

---

streamly.cabal

Second level bullets are not rendered properly so use a separate
paragraph instead to avoid the issue.

Reformat and compact the description

---

src/Streamly/Internal/Data/Stream/IsStream/Enumeration.hs
src/Streamly/Internal/Data/Stream/IsStream/Expand.hs
src/Streamly/Internal/Data/Stream/IsStream/Generate.hs
src/Streamly/Internal/Data/Stream/IsStream/Reduce.hs
src/Streamly/Internal/Data/Stream/IsStream/Transform.hs
src/Streamly/Prelude.hs

Use full module names in documentation

---

benchmark/Chart.hs

For case insensitive comparison we were lowercasing the fields in the
benchmark csv header but not the fields being compared. So the fields
were not matching if we passed them in mixed case.

Use lowercased comparison for benchmark fields

---

streamly.cabal

Follows #933, which only works for other OSes.

Bump Win32 upper bound to work with GHC 9.0

---

benchmark/Streamly/Benchmark/Prelude/Serial/Elimination.hs
bin/bench-exec-one.sh

Move showInstance benchmark for pure streams to o-n-space
Increase the heap space for array map x 4

Fix the space requirements of two benchmarks

---

default.nix

To remind us the shell we are in if we change directories.

Add a streamly tag in nix-shell prompt

---

benchmark/bench-report/bin/bench-runner.sh
bin/test.sh

Otherwise we may accidentally run into memory hog issues.

Use limit-build-mem by default in bench/test scripts

---

src/Streamly/Internal/Data/Stream/IsStream/Expand.hs
src/Streamly/Internal/Data/Stream/IsStream/Top.hs
src/Streamly/Internal/Data/Stream/StreamK.hs

* Optimize StreamK.mergeBy
* Use StreamK.mergeBy as default
* Add a separate combinator to use StreamD.mergeBy

Optimize and use StreamK.mergeBy as default

---

Changelog.md
benchmark/bench-report/bin/build-lib.sh
bin/test.sh
src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
src/Streamly/Internal/Data/Array/Stream/Foreign.hs
src/Streamly/Internal/System/IO.hs

Also fix a bug where we were using chunk size in bytes as element count.

Ensure minimum chunk size of one element

---

Changelog.md
src/Streamly/Internal/Data/Array/Foreign.hs
src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
src/Streamly/Internal/Data/Array/Foreign/Type.hs
src/Streamly/Internal/Data/Array/Stream/Fold/Foreign.hs
src/Streamly/Internal/Data/Array/Stream/Foreign.hs
src/Streamly/Internal/FileSystem/FD.hs
src/Streamly/Internal/FileSystem/Handle.hs
src/Streamly/Internal/Network/Socket.hs
src/Streamly/Internal/Ring/Foreign.hs
src/Streamly/Internal/System/IOVec.hs
src/Streamly/Internal/Unicode/Stream.hs

Adding a touchForeignPtr led to significant regressions. Fixing that required a bigger change to use a simpler type in the array instead of using ForeignPtr.

Fix missing touch

---

src/Streamly/Internal/Data/Array/Foreign.hs
src/Streamly/Internal/Data/Array/Foreign/Mut.hs
src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
src/Streamly/Internal/Data/Array/Foreign/Type.hs

Remove all unsafe IO from Array.Foreign.Mut.Type

---

streamly.cabal

Otherwise hackage rejects the package.
cc @hasufell

Define exposed module under a single condition

---

test/Streamly/Test/FileSystem/Event/Darwin.hs

The test is unpredictable as we create the watch dir before starting the
watch, we may miss the event.

Comment out incorrect test

---

benchmark/Streamly/Benchmark/Prelude/ZipAsync.hs
docs/ConcurrentStreams.hs
src/Streamly/Internal/Data/Stream/Zip.hs
test/Streamly/Test/Prelude/Async.hs

This is a breaking change as it modifies the behavior of `<*>` in `ZipAsyncM`

Fix and test for concurrent applicative

---

src/Streamly/Internal/Data/Array/Foreign/Type.hs
src/Streamly/Internal/Data/Array/Stream/Foreign.hs

Is this a breaking change? We have relaxed the constraint so it should admit everything as before. It may result in a warning about redundant constraints though.

Remove MonadIO constraint

---

src/Streamly/Internal/Data/Time/Clock.hs

I added this to implement `chunksOfTimeout` as mentioned in issue #456 . But that combinator is not yet implemented using this. The idea is to start a periodic timer, emit chunks of `n` elements from the stream whenever the chunk is complete or whenever a timeout occurs, however, if the chunk got completed we need to reset the timer.

Add adjustable timers

---

benchmark/streamly-benchmarks.cabal
docs/streamly-docs.cabal
streamly.cabal
test/streamly-tests.cabal

- Used in normalization combinators
- Essentially the normalization helpers did not change over the versions
- Admit 0.3.*

Bump the upper bound of unicode-data

---

.packcheck.ignore
bin/run-repl-quick.sh

Running this in a loop in a smart way will work like `ghcid`.
The idea is to have an extremely light version of `run-ci.sh`
This can be very helpful in any refactoring change.
This script should be majorly improved but it solves my use case for the time being.
This need not even be merged if we think this will cause some maintenance burden. I'm not going to work on this script for the time being. All improvements are postponed to a later date. If anyone wants to just quickly use it, they can!

Add a dumb script to repl all the executables and library

---

src/Streamly/Internal/Data/Array/Stream/Foreign.hs
src/Streamly/Internal/Data/Fold/Type.hs
src/Streamly/Internal/Data/Parser/ParserD.hs
src/Streamly/Internal/Data/Parser/ParserD/Type.hs
src/Streamly/Internal/Data/Producer/Source.hs
src/Streamly/Internal/Data/Stream/StreamD/Eliminate.hs

They seem to do find without it. In some cases wrong INLINE causes perf
issues.

GHC-9: Remove INLINE on mutually rec funcs

---

src/Streamly/Internal/Data/Array/Foreign.hs
src/Streamly/Internal/Data/Array/Stream/Mut/Foreign.hs
src/Streamly/Internal/Data/Stream/StreamD/Generate.hs
src/Streamly/Internal/System/IOVec.hs

These modules will be part of the lower level package streamly-core so should not depend on higher level ones.

Remove dependency of lower level modules on higher level ones

---

src/Streamly/Internal/Data/Stream/IsStream/Expand.hs
src/Streamly/Internal/Data/Stream/IsStream/Type.hs
src/Streamly/Internal/Data/Stream/Zip.hs
src/Streamly/Internal/Data/Stream/ZipAsync.hs
streamly.cabal

So that we can move concurrent streams functionality out of the
streamly-core package.

Split Zip module into Zip and ZipAsync

---

src/Streamly/Internal/Control/Concurrent.hs
src/Streamly/Internal/Control/ForkLifted.hs
src/Streamly/Internal/Data/Fold/Async.hs
src/Streamly/Internal/Data/IOFinalizer.hs
src/Streamly/Internal/Data/SVar.hs
src/Streamly/Internal/Data/SVar/Dispatch.hs
src/Streamly/Internal/Data/SVar/Type.hs
src/Streamly/Internal/Data/Stream/Ahead.hs
src/Streamly/Internal/Data/Stream/Async.hs
src/Streamly/Internal/Data/Stream/IsStream/Exception.hs
src/Streamly/Internal/Data/Stream/SVar/Generate.hs
src/Streamly/Internal/Data/Stream/StreamD/Exception.hs
src/Streamly/Internal/Data/Unfold.hs
streamly.cabal

Just a little experiment to see what it would look like if monad-control was replaced

Allow using unliftio-core instead of monad-control

---

dev/MAINTAINING.md

Create a version tag once the candidate is verified and the package in uploaded.

Shift the order of tasks in the release checklist

---

src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
src/Streamly/Internal/Data/Array/Foreign/Type.hs
src/Streamly/Internal/FileSystem/File.hs
src/Streamly/Internal/FileSystem/Handle.hs

This remove `Storable` constraint from exposed APIs so targeted to 0.9.0.

Use byteLength instead of length in putChunk

---

benchmark/Streamly/Benchmark/Data/Fold.hs
benchmark/streamly-benchmarks.cabal
core/src/Streamly/Internal/Data/Fold.hs
core/src/Streamly/Internal/Data/IsMap.hs
core/streamly-core.cabal
streamly.cabal

IntMap and HashMap can provide better performance than Map.
Also, allow mutable cells in classify for better performance.

Allow different types of Map in classify

---

benchmark/Streamly/Benchmark/Data/Fold.hs
core/src/Streamly/Internal/Data/Fold.hs
test/Streamly/Test/Data/Fold.hs

We may want to use the entire value to determine the fold and not just
the key. For example, we may have the key as an Int that uniquely
determines the fold (for example a connection/request id). Once the
fold starts we can always lookup the fold using this key. However, to
determine what fold to use initially we may need more information than
just the request-id (e.g. the type of the message).

Use the demux input to determine the fold

---

benchmark/Streamly/Benchmark/Data/Parser.hs
core/src/Streamly/Internal/Data/Stream/StreamK.hs
src/Streamly/Internal/Data/Stream/IsStream/Eliminate.hs

Replacement of #1626 which got closed and github does not allow it to be opened.

Use a CPS implementation for parseBreak for linear performance

---

benchmark/Streamly/Benchmark/Data/Array/Stream/Foreign.hs
src/Streamly/Internal/Data/Array/Stream/Foreign.hs

This allows us to break array streams very efficiently with linear performance characteristics.

Fold array streams using regular folds (CPS implementation)

---

.github/workflows/haskell.yml
benchmark/Streamly/Benchmark/Prelude/Serial/Split.hs
core/src/Streamly/Internal/Data/Fold.hs
src/Streamly/Internal/Data/Stream/IsStream/Common.hs
src/Streamly/Internal/Data/Stream/IsStream/Reduce.hs
test/Streamly/Test/Prelude/Serial.hs

Commit by commit review may work better, 3rd and 4th commits are the important ones.
I have added commented out stream splitting operations in terms of the fold operations. The stream tests pass with those operations. Measured performance with those definitions enabled and compared it to the earlier versions of these operations. Allocations are the same, however, CPU performance is not as good for one of the operations, though it is quite good in absolute sense.
```
Prelude.Serial(cpuTime)
Benchmark                                                                                                     default(0)(ms) default(1) - default(0)(%)
------------------------------------------------------------------------------------------------------------- -------------- -------------------------- …
```

Implement folds for substring matching

---

.github/workflows/regression-check.yml

Sometimes the github CI runs on an incorrect branch/commit. We need a way to manually run the CI on a specific commit.

Make regression checking CI dispatchable manually

---

core/streamly-core.cabal

See https://github.com/haskell/cabal/issues/8406
The issue is easily reproduced by running `cabal install --lib --env=/dev/null core/`. `cabal install` first does a sdist, then installs it, so it catches missing `extra-source-files` etc

core: add assert.hs to extra-source-files

---

benchmark/Streamly/Benchmark/Data/Fold.hs
core/src/Streamly/Data/Stream.hs
core/src/Streamly/Internal/Data/Fold.hs
core/src/Streamly/Internal/Data/Fold/Type.hs
core/src/Streamly/Internal/Data/Fold/Window.hs
core/src/Streamly/Internal/Data/Stream/Bottom.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Transform.hs
core/src/Streamly/Internal/Data/Stream/Transform.hs

Usable across folds and streams. Implemented common transformations
using scans. Performance of single operation benchmark seems to be
unaffected but in some cases combinations of multiple benchmarks or the
same oepration multiple times is degraded.
The perf impact could perhaps be improved if we have a separate Scan
type where we do not need a pre initialization of state.

Add modular scanning functions for transformations

---

.github/workflows/regression-check.yml
src/Streamly/Internal/Data/Stream/Async/Channel.hs
src/Streamly/Internal/Data/Stream/Async/Channel/Append.hs
src/Streamly/Internal/Data/Stream/Async/Channel/Consumer.hs
src/Streamly/Internal/Data/Stream/Async/Channel/Dispatcher.hs
src/Streamly/Internal/Data/Stream/Async/Channel/Interleave.hs
src/Streamly/Internal/Data/Stream/Async/Channel/Operations.hs
src/Streamly/Internal/Data/Stream/Async/Channel/Type.hs
src/Streamly/Internal/Data/Stream/Channel/Dispatcher.hs
src/Streamly/Internal/Data/Stream/Channel/Types.hs
src/Streamly/Internal/Data/Stream/Channel/Worker.hs
streamly.cabal

Move out the common data structures and functions from Async module to Data.Stream.Channel module. The common code will be used in Parallel module.
Concrete channel type remains in the Async module, but the parts that are used to make it up are in the common module.

Refactor Async Channel code for reuse in other stream types

---

core/src/Streamly/Data/Array/Unboxed/Mut.hs
core/src/Streamly/Internal/Data/Array/Unboxed.hs
core/src/Streamly/Internal/Data/Array/Unboxed/Mut/Type.hs
core/src/Streamly/Internal/Data/Array/Unboxed/Stream.hs
core/src/Streamly/Internal/Data/Array/Unboxed/Type.hs
core/src/Streamly/Internal/Data/Fold.hs
core/src/Streamly/Internal/Data/IORef/Unboxed.hs
core/src/Streamly/Internal/Data/Ring/Unboxed.hs
core/src/Streamly/Internal/Data/Unboxed.hs
core/src/Streamly/Internal/FileSystem/Handle.hs
src/Streamly/Internal/FileSystem/FD.hs
src/Streamly/Internal/Network/Socket.hs
test/Streamly/Test/Data/Array/Unboxed.hs
test/Streamly/Test/Data/Array/Unboxed/Mut.hs

Added Unboxed.newUnpinnedBytes and Mut.Type.newUnpinnedArray
Array.Unboxed.Mut.Type.nilArrayContents -> Unboxed.nil Array.Unboxed.Mut.Type.newAlignedArrayContents -> Unboxed.newAlignedPinnedBytes
Mut.Type:
newArray -> newPinnedArray
newArrayAligned -> newAlignedPinnedArray
Unboxed:
newUnpinnedArrayContents -> newUnpinnedBytes

Rename and move unboxed array APIs

---

core/src/Streamly/Internal/Data/Stream/Exception.hs

It bundles an unnecessary MonadThrow in some cases which also makes us wonder what requires MonadThrow.

Remove MonadAsync constraint from exception ops

---

streamly.cabal

All these modules are to be deprecated after ensuring that all equivalent functionality is available in other modules.

Move IsStream modules to deprecated section

---

benchmark/Streamly/Benchmark/Data/Parser.hs
benchmark/Streamly/Benchmark/Data/Parser/ParserD.hs
core/src/Streamly/Data/Parser.hs
core/src/Streamly/Internal/Data/Parser.hs
core/src/Streamly/Internal/Data/Parser/ParserD.hs
core/src/Streamly/Internal/Unicode/Char/Parser.hs

Rename:
element -> oneEq
except -> oneNotEq
eqBy -> listEqBy
matchBy -> eqBy
Change the signature of eqBy to return the list.

Rename some parsers

---

src/Streamly/Internal/Network/Inet/TCP.hs
src/Streamly/Internal/Network/Socket.hs
src/Streamly/Network/Inet/TCP.hs
src/Streamly/Network/Socket.hs
test/Streamly/Test/Network/Inet/TCP.hs
test/Streamly/Test/Network/Socket.hs

Add stream generating operations as alternatives to unfolds. Stream
opertions are for common use. Unfolds are for optimizations in nested
use.
Rename the fold operations from "write*" to "put*". The "write*"
operations can be used for "Refold"s in future.

Add stream ops and rename fold ops in the network module

---

src/Streamly/Internal/FileSystem/Dir.hs
src/Streamly/Internal/FileSystem/Event/Linux.hs
src/Streamly/Internal/FileSystem/Event/Windows.hs
src/Streamly/Internal/FileSystem/File.hs

Also add deprecated versions of renamed APIs in the FileSystem.File module.

Rename unfold APIs in the FileSystem.Dir module

---

core/src/Streamly/Data/Array/Unboxed.hs
core/src/Streamly/Internal/Data/Array/Mut/Type.hs
core/src/Streamly/Internal/Data/Fold.hs
core/src/Streamly/Internal/Data/Fold/Type.hs
core/src/Streamly/Internal/Data/Parser.hs
core/src/Streamly/Internal/Data/Parser/ParserD.hs
core/src/Streamly/Internal/Data/Parser/ParserD/Type.hs
core/src/Streamly/Internal/Data/Refold/Type.hs
core/src/Streamly/Internal/Data/Stream/Expand.hs
core/src/Streamly/Internal/Unicode/String.hs
src/Streamly/Internal/Network/Socket.hs

- Make streamly-core docspec independent of streamly
- Fix the example in Streamly.Network.Socket module

Fixing minor release issues

---

core/src/Streamly/Internal/Data/Array/Unboxed/Stream.hs
core/src/Streamly/Internal/Data/Parser/ParserD/Type.hs
core/src/Streamly/Internal/Data/Parser/ParserK/Type.hs
core/src/Streamly/Internal/Data/Producer/Source.hs
core/src/Streamly/Internal/Data/Stream/Eliminate.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Eliminate.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Nesting.hs
core/src/Streamly/Internal/Data/Stream/StreamK.hs

It can happen if the first parser in an alternative does not receive sufficient input but the next parser can work even without input.

Allow "Continue 0" case in parser extract

---

benchmark/Streamly/Benchmark/Data/Array/Stream.hs

**parseBreak (recursive, small arrays):** hangs for ever.

Fix benchmark error in Data.Array.Stream

---

docs/User/Tutorials/getting-started.md

* Replace detailed instructions about installing haskell/cabal by a pointer to the Haskell downloads page
* Add a section about complete dev environment using a nix shell
* Add the REPL section first, without depending on the project setup
* Adapt for new changes in the packages structure, streamly-core and streamly

Update getting-started guide

---

benchmark/Streamly/Benchmark/FileSystem/Handle/Read.hs
core/src/Streamly/Data/Fold.hs
core/src/Streamly/Internal/Data/Fold.hs
core/src/Streamly/Internal/Data/Fold/Type.hs
core/src/Streamly/Internal/Data/Stream/Chunked.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Nesting.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Type.hs
core/src/Streamly/Internal/FileSystem/Dir.hs
core/src/Streamly/Internal/FileSystem/File.hs
core/src/Streamly/Internal/FileSystem/Handle.hs
docs/User/ProjectRelated/Changelog.md
src/Streamly/Internal/Data/Stream/IsStream/Reduce.hs
src/Streamly/Internal/Network/Inet/TCP.hs
src/Streamly/Internal/Network/Socket.hs

* Deprecate chunksOf in Data.Fold as it is exposed.
* No deprecation is required in Data.Stream as it is a new module.

Rename chunksOf to groupsOf

---

src/Streamly/Internal/Control/ForkLifted.hs
src/Streamly/Internal/Data/Fold/Concurrent.hs
src/Streamly/Internal/Data/Fold/Concurrent/Channel.hs
src/Streamly/Internal/Data/Fold/Concurrent/Channel/Type.hs
src/Streamly/Internal/Data/Stream/Channel/Types.hs

(My use case: Concurrently running multiple folds (put together with `demux`) on bound threads.)
I have tried to make this change unintrusive: The new `bound` flag is only exposed in `*Fold.Concurrent*` and all existing calls to `doFork` (apart from the one in `*Fold.Concurrent*`) look exactly the same as before.
Adding `bound` support everywhere would apparently require more sweeping changes in the codebase (adding an extra `Bool` parameter to all sorts of functions, etc.), so I hesitated to do this for now. If this is something you really would prefer at this time, or if you have any other suggestions for improvements, feel free to let me know.

Add bound config param & expose for concurrent folds

---

core/src/Streamly/Data/Fold.hs
core/src/Streamly/Internal/Data/Array/Generic.hs
core/src/Streamly/Internal/Data/Array/Mut/Type.hs
core/src/Streamly/Internal/Data/Array/Type.hs
core/src/Streamly/Internal/Data/Fold.hs
core/src/Streamly/Internal/Data/Fold/Container.hs
core/src/Streamly/Internal/Data/Fold/Type.hs
core/src/Streamly/Internal/Data/Refold/Type.hs
core/src/Streamly/Internal/Data/Stream/Common.hs
core/src/Streamly/Internal/Data/Stream/StreamD/Eliminate.hs
core/src/Streamly/Internal/Data/Stream/StreamK.hs

See https://github.com/haskell/core-libraries-committee/issues/167
This is, of course, a bit speculative at the moment, but given that the change does not involve CPP, it should not hurt to merge it early to simplify further impact assessment.
This PR covers `streamly-core` only: `streamly` itself does not seem to be buildable with GHC 9.6, even less so with GHC HEAD.

Future-proof against potential Prelude.foldl'

---

benchmark/Streamly/Benchmark/Data/Stream/Common.hs
benchmark/Streamly/Benchmark/Data/Stream/StreamK.hs
src/Streamly/Internal/Data/Stream/IsStream/Eliminate.hs
src/Streamly/Internal/Data/Stream/IsStream/Top.hs
src/Streamly/Internal/Data/Stream/IsStream/Type.hs
src/Streamly/Prelude.hs

Continuing #2414. 
I built a patched GHC 9.4 to be able to complete an impact assessment without waiting for #2415. This patch now covers `streamly` package itself and all the rest of the repo.

Future-proof against potential Prelude.foldl' - part 2

---

core/src/Streamly/Internal/Data/MutArray.hs
core/src/Streamly/Internal/Data/MutArray/Stream.hs
core/src/Streamly/Internal/Data/MutArray/Type.hs

Move the mut array compaction funcs from MutArray.Stream to MutArray module.

Deprecate MutArray/Stream module, move funcs to MutArray module

---

benchmark/Streamly/Benchmark/Data/Ring/Unboxed.hs
core/docs/Changelog.md
core/src/Streamly/Internal/Data/Array.hs
core/src/Streamly/Internal/Data/Array/ArrayMacros.h
core/src/Streamly/Internal/Data/Fold/Combinators.hs
core/src/Streamly/Internal/Data/Fold/Window.hs
core/src/Streamly/Internal/Data/Ring.hs
core/src/Streamly/Internal/Data/Stream/Eliminate.hs
core/src/Streamly/Internal/Data/Stream/Nesting.hs
src/Streamly/Internal/Data/Stream/IsStream/Common.hs
src/Streamly/Internal/Data/Stream/IsStream/Reduce.hs
test/Streamly/Test/Data/Ring/Unboxed.hs
test/Streamly/Test/Prelude/Serial.hs

This looks suspiciously good.
```
Generating reports for Data.Ring.Unboxed...
Data.Ring.Unboxed(cpuTime)
Benchmark                                      default(0)(ms) default(1) - default(0)(%)
---------------------------------------------- -------------- --------------------------
All.Data.Ring.Unboxed/o-1-space.unsafeEqArray            5.55                    -566.29
All.Data.Ring.Unboxed/o-1-space.unsafeEqArrayN           1.01                    -960.54
Data.Ring.Unboxed(Allocated)
Benchmark                                      default(0)(MiB) default(1) - default(0)(%)
---------------------------------------------- --------------- --------------------------
All.Data.Ring.Unboxed/o-1-space.unsafeEqArray            24.33                  -Infinity …
```

Use MutableByteArray as the primitive for the ring buffer

---

.github/workflows/haskell.yml
benchmark/Streamly/Benchmark/Data/Fold.hs
core/src/Streamly/Data/MutByteArray.hs
core/src/Streamly/Internal/Data/Array/Type.hs
core/src/Streamly/Internal/Data/MutArray/Lib.c
core/src/Streamly/Internal/Data/MutArray/Type.hs
core/src/Streamly/Internal/Data/MutByteArray/Type.hs
core/streamly-core.cabal
stack.yaml
test/Streamly/Test/Data/Array.hs
test/Streamly/Test/FileSystem/Event/Linux.hs

Pass the MutableByteArray# directly to the FFI functions to avoid garbage collector moving it between the time we get a pointer and then call the FFI function.

Fix unsafe use of FFI for unpinned arrays

---

core/src/Streamly/Data/MutArray.hs
core/src/Streamly/Data/MutArray/Generic.hs
core/src/Streamly/Internal/Data/Array/Generic.hs
core/src/Streamly/Internal/Data/MutArray/Generic.hs
core/src/Streamly/Internal/Data/ParserK/Type.hs
core/src/Streamly/Internal/Data/Ring/Generic.hs
test/Streamly/Test/FileSystem/Event/Common.hs
test/Streamly/Test/FileSystem/Event/Linux.hs

Earlier:
* We deprecated the existing APIs but missed exporting the new ones.
* We missed renaming/deprecating the Generic MutArray APIs

Fix deprecations in MutArray and MutArray/Generic

---

core/src/Streamly/Internal/Data/Scanl/Window.hs

Used `Replace1` to ensure all the followup changes.

Flip the argument order of Replace in window folds

---

core/docs/Changelog.md
src/Streamly/Internal/FileSystem/Event.hs
src/Streamly/Internal/FileSystem/Event/Darwin.hs
src/Streamly/Internal/FileSystem/Event/Linux.hs
src/Streamly/Internal/FileSystem/Event/Windows.hs
test/Streamly/Test/FileSystem/Event.hs
test/Streamly/Test/FileSystem/Event/Darwin.hs
test/Streamly/Test/FileSystem/Event/Linux.hs
test/Streamly/Test/FileSystem/Event/Windows.hs

Deprecate the FileSystem.Event and friends

---

core/src/Streamly/Internal/Data/Stream/Transformer.hs

This PR changes two characters to generalize the type of `usingStateT`, making it possible to use it with functions that arbitrarily transform the items in a stream.
Here's an example motivating the need for this change. I rely on the below function to transform streams in a manner in which each item in a stream can be mapped to a new value that depends on an arbitrary state (which is typically built up from previous items in the stream):
```
import qualified Streamly.Data.Stream.Prelude  as S
import qualified Streamly.Internal.Data.Stream as S
stateMap
:: Monad m => (a -> StateT s m (Maybe b)) -> s -> Stream m a -> Stream m b
stateMap f s = S.catMaybes . S.evalStateT (return s) . S.mapM f . S.liftInner
```
It should be possible to refactor this function as `stateMap f s = S.catMaybes . …

Generalize type signature of `usingStateT`

---

src/Streamly/Internal/Data/Fold/Prelude.hs
src/Streamly/Internal/Data/Fold/SVar.hs
src/Streamly/Internal/Data/SVar.hs
src/Streamly/Internal/Data/SVar/Dispatch.hs
src/Streamly/Internal/Data/SVar/Pull.hs
src/Streamly/Internal/Data/SVar/Worker.hs
src/Streamly/Internal/Data/Stream/SVar.hs
src/Streamly/Internal/Data/Stream/SVar/Eliminate.hs
src/Streamly/Internal/Data/Stream/SVar/Generate.hs
src/Streamly/Internal/Data/Unfold/Prelude.hs
src/Streamly/Internal/Data/Unfold/SVar.hs

Is there replacement for the behaviour in `Streamly.Internal.Data.Unfold.SVar`
and `Streamly.Internal.Data.Fold.SVar`?
If not, we can create the same APIs replacing `SVar` with `Channel`.
Replace:

Deprecate all the modules related to SVar

---

benchmark/Streamly/Benchmark/Data/MutArray.hs
core/src/Streamly/Internal/Data/Array.hs
core/src/Streamly/Internal/Data/Array/Generic.hs
core/src/Streamly/Internal/Data/Array/Type.hs
core/src/Streamly/Internal/Data/MutArray.hs
core/src/Streamly/Internal/Data/MutArray/Generic.hs
core/src/Streamly/Internal/Data/MutArray/Type.hs
core/src/Streamly/Internal/Data/StreamK.hs
core/src/Streamly/Internal/FileSystem/Path/Common.hs
core/src/Streamly/Internal/Unicode/Stream.hs
src/Streamly/Internal/FileSystem/Event/Linux.hs
test/Streamly/Test/Data/Array.hs

break -> into 2 parts
split -> into many parts
strip* -> dropWhile*

Rename multiple array APIs based on certain conventions

---

benchmark/Streamly/Benchmark/Data/ParserK.hs
benchmark/streamly-benchmarks.cabal
core/src/Streamly/Data/Parser.hs
core/src/Streamly/Data/ParserK.hs
core/src/Streamly/Data/StreamK.hs
core/src/Streamly/Internal/Data/Array.hs
core/src/Streamly/Internal/Data/Array/Generic.hs
core/src/Streamly/Internal/Data/ParserK.hs
core/src/Streamly/Internal/Data/ParserK/Type.hs
core/src/Streamly/Internal/Data/StreamK.hs
core/src/Streamly/Internal/Data/StreamK/Type.hs
hie.yaml
test/Streamly/Test/Data/Parser.hs
test/Streamly/Test/Data/ParserK.hs

https://github.com/composewell/streamly/issues/2663

Move array stream parsing funcs to array modules

---

core/src/Streamly/Internal/FileSystem/Path/Common.hs
core/src/Streamly/Internal/FileSystem/PosixPath.hs
core/src/Streamly/Internal/FileSystem/WindowsPath.hs

issue https://github.com/composewell/streamly/issues/3022

Do not return empty path in splitExtension

---

core/src/Streamly/FileSystem/Path.hs
core/src/Streamly/FileSystem/Path/Node.hs
core/src/Streamly/FileSystem/Path/Seg.hs
core/src/Streamly/FileSystem/Path/SegNode.hs
core/src/Streamly/Internal/FileSystem/DirIO.hs
core/src/Streamly/Internal/FileSystem/Posix/ReadDir.hsc
core/src/Streamly/Internal/FileSystem/PosixPath.hs
core/src/Streamly/Internal/FileSystem/PosixPath/Node.hs
core/src/Streamly/Internal/FileSystem/PosixPath/Seg.hs
core/src/Streamly/Internal/FileSystem/PosixPath/SegNode.hs
core/src/Streamly/Internal/FileSystem/WindowsPath.hs

issue https://github.com/composewell/streamly/issues/3023

Rename "append" to "extend" in the Path modules

---

core/src/Streamly/Internal/Data/IORef.hs
core/src/Streamly/Internal/Data/MutArray.hs
src/Streamly/Internal/Data/Stream/Concurrent.hs

issue https://github.com/composewell/streamly/issues/2964

Change the signature of pollIntIORef

---

benchmark/bench-runner/Main.hs
core/docs/Changelog.md
core/src/Streamly/Internal/Data/Stream/Exception.hs
src/Streamly/Internal/Control/ForkLifted.hs
src/Streamly/Internal/Data/Channel/Dispatcher.hs
src/Streamly/Internal/Data/Channel/Types.hs
src/Streamly/Internal/Data/Channel/Worker.hs
src/Streamly/Internal/Data/Stream/Channel.hs
src/Streamly/Internal/Data/Stream/Channel/Append.hs
src/Streamly/Internal/Data/Stream/Channel/Consumer.hs
src/Streamly/Internal/Data/Stream/Channel/Dispatcher.hs
src/Streamly/Internal/Data/Stream/Channel/Interleave.hs
src/Streamly/Internal/Data/Stream/Channel/Operations.hs
src/Streamly/Internal/Data/Stream/Channel/Type.hs
test/Streamly/Test/Data/Stream/Exception.hs
test/streamly-tests.cabal

See also: https://github.com/composewell/streamly/issues/3039 for a small enhancement.

 Add prompt resource cleanup functionality

---

test/Streamly/Test/FileSystem/Event/Linux.hs
test/streamly-tests.cabal

We now have a GHC with instrumented RTS to debug the issue, so enabling these.

Enable some fsevent tests

---

core/src/Streamly/Data/Stream.hs

We can just use `fairCross` followed by `map` and it should fuse.

Do not expose fairCrossWith
